// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/emailtemplate"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharedlink"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharepolicy"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	emailtemplateMixin := schema.EmailTemplate{}.Mixin()
	emailtemplate.Policy = privacy.NewPolicies(emailtemplateMixin[3], schema.EmailTemplate{})
	emailtemplate.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := emailtemplate.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	emailtemplateMixinFields3 := emailtemplateMixin[3].Fields()
	_ = emailtemplateMixinFields3
	emailtemplateFields := schema.EmailTemplate{}.Fields()
	_ = emailtemplateFields
	// emailtemplateDescTenantID is the schema descriptor for tenant_id field.
	emailtemplateDescTenantID := emailtemplateMixinFields3[0].Descriptor()
	// emailtemplate.DefaultTenantID holds the default value on creation for the tenant_id field.
	emailtemplate.DefaultTenantID = emailtemplateDescTenantID.Default.(uint32)
	// emailtemplateDescName is the schema descriptor for name field.
	emailtemplateDescName := emailtemplateFields[1].Descriptor()
	// emailtemplate.NameValidator is a validator for the "name" field. It is called by the builders before save.
	emailtemplate.NameValidator = func() func(string) error {
		validators := emailtemplateDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// emailtemplateDescSubject is the schema descriptor for subject field.
	emailtemplateDescSubject := emailtemplateFields[2].Descriptor()
	// emailtemplate.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	emailtemplate.SubjectValidator = func() func(string) error {
		validators := emailtemplateDescSubject.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(subject string) error {
			for _, fn := range fns {
				if err := fn(subject); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// emailtemplateDescHTMLBody is the schema descriptor for html_body field.
	emailtemplateDescHTMLBody := emailtemplateFields[3].Descriptor()
	// emailtemplate.HTMLBodyValidator is a validator for the "html_body" field. It is called by the builders before save.
	emailtemplate.HTMLBodyValidator = emailtemplateDescHTMLBody.Validators[0].(func(string) error)
	// emailtemplateDescIsDefault is the schema descriptor for is_default field.
	emailtemplateDescIsDefault := emailtemplateFields[4].Descriptor()
	// emailtemplate.DefaultIsDefault holds the default value on creation for the is_default field.
	emailtemplate.DefaultIsDefault = emailtemplateDescIsDefault.Default.(bool)
	// emailtemplateDescID is the schema descriptor for id field.
	emailtemplateDescID := emailtemplateFields[0].Descriptor()
	// emailtemplate.IDValidator is a validator for the "id" field. It is called by the builders before save.
	emailtemplate.IDValidator = emailtemplateDescID.Validators[0].(func(string) error)
	sharepolicyMixin := schema.SharePolicy{}.Mixin()
	sharepolicy.Policy = privacy.NewPolicies(sharepolicyMixin[2], schema.SharePolicy{})
	sharepolicy.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := sharepolicy.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	sharepolicyMixinFields2 := sharepolicyMixin[2].Fields()
	_ = sharepolicyMixinFields2
	sharepolicyFields := schema.SharePolicy{}.Fields()
	_ = sharepolicyFields
	// sharepolicyDescTenantID is the schema descriptor for tenant_id field.
	sharepolicyDescTenantID := sharepolicyMixinFields2[0].Descriptor()
	// sharepolicy.DefaultTenantID holds the default value on creation for the tenant_id field.
	sharepolicy.DefaultTenantID = sharepolicyDescTenantID.Default.(uint32)
	// sharepolicyDescShareLinkID is the schema descriptor for share_link_id field.
	sharepolicyDescShareLinkID := sharepolicyFields[1].Descriptor()
	// sharepolicy.ShareLinkIDValidator is a validator for the "share_link_id" field. It is called by the builders before save.
	sharepolicy.ShareLinkIDValidator = func() func(string) error {
		validators := sharepolicyDescShareLinkID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(share_link_id string) error {
			for _, fn := range fns {
				if err := fn(share_link_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sharepolicyDescValue is the schema descriptor for value field.
	sharepolicyDescValue := sharepolicyFields[4].Descriptor()
	// sharepolicy.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	sharepolicy.ValueValidator = func() func(string) error {
		validators := sharepolicyDescValue.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(value string) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sharepolicyDescReason is the schema descriptor for reason field.
	sharepolicyDescReason := sharepolicyFields[5].Descriptor()
	// sharepolicy.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	sharepolicy.ReasonValidator = sharepolicyDescReason.Validators[0].(func(string) error)
	// sharepolicyDescID is the schema descriptor for id field.
	sharepolicyDescID := sharepolicyFields[0].Descriptor()
	// sharepolicy.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sharepolicy.IDValidator = sharepolicyDescID.Validators[0].(func(string) error)
	sharedlinkMixin := schema.SharedLink{}.Mixin()
	sharedlink.Policy = privacy.NewPolicies(sharedlinkMixin[2], schema.SharedLink{})
	sharedlink.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := sharedlink.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	sharedlinkMixinFields2 := sharedlinkMixin[2].Fields()
	_ = sharedlinkMixinFields2
	sharedlinkFields := schema.SharedLink{}.Fields()
	_ = sharedlinkFields
	// sharedlinkDescTenantID is the schema descriptor for tenant_id field.
	sharedlinkDescTenantID := sharedlinkMixinFields2[0].Descriptor()
	// sharedlink.DefaultTenantID holds the default value on creation for the tenant_id field.
	sharedlink.DefaultTenantID = sharedlinkDescTenantID.Default.(uint32)
	// sharedlinkDescResourceID is the schema descriptor for resource_id field.
	sharedlinkDescResourceID := sharedlinkFields[2].Descriptor()
	// sharedlink.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	sharedlink.ResourceIDValidator = func() func(string) error {
		validators := sharedlinkDescResourceID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_id string) error {
			for _, fn := range fns {
				if err := fn(resource_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sharedlinkDescResourceName is the schema descriptor for resource_name field.
	sharedlinkDescResourceName := sharedlinkFields[3].Descriptor()
	// sharedlink.ResourceNameValidator is a validator for the "resource_name" field. It is called by the builders before save.
	sharedlink.ResourceNameValidator = func() func(string) error {
		validators := sharedlinkDescResourceName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(resource_name string) error {
			for _, fn := range fns {
				if err := fn(resource_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sharedlinkDescToken is the schema descriptor for token field.
	sharedlinkDescToken := sharedlinkFields[4].Descriptor()
	// sharedlink.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	sharedlink.TokenValidator = func() func(string) error {
		validators := sharedlinkDescToken.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(token string) error {
			for _, fn := range fns {
				if err := fn(token); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sharedlinkDescRecipientEmail is the schema descriptor for recipient_email field.
	sharedlinkDescRecipientEmail := sharedlinkFields[7].Descriptor()
	// sharedlink.RecipientEmailValidator is a validator for the "recipient_email" field. It is called by the builders before save.
	sharedlink.RecipientEmailValidator = func() func(string) error {
		validators := sharedlinkDescRecipientEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(recipient_email string) error {
			for _, fn := range fns {
				if err := fn(recipient_email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sharedlinkDescMessage is the schema descriptor for message field.
	sharedlinkDescMessage := sharedlinkFields[8].Descriptor()
	// sharedlink.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	sharedlink.MessageValidator = sharedlinkDescMessage.Validators[0].(func(string) error)
	// sharedlinkDescTemplateID is the schema descriptor for template_id field.
	sharedlinkDescTemplateID := sharedlinkFields[9].Descriptor()
	// sharedlink.TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	sharedlink.TemplateIDValidator = sharedlinkDescTemplateID.Validators[0].(func(string) error)
	// sharedlinkDescViewed is the schema descriptor for viewed field.
	sharedlinkDescViewed := sharedlinkFields[10].Descriptor()
	// sharedlink.DefaultViewed holds the default value on creation for the viewed field.
	sharedlink.DefaultViewed = sharedlinkDescViewed.Default.(bool)
	// sharedlinkDescViewedIP is the schema descriptor for viewed_ip field.
	sharedlinkDescViewedIP := sharedlinkFields[12].Descriptor()
	// sharedlink.ViewedIPValidator is a validator for the "viewed_ip" field. It is called by the builders before save.
	sharedlink.ViewedIPValidator = sharedlinkDescViewedIP.Validators[0].(func(string) error)
	// sharedlinkDescRevoked is the schema descriptor for revoked field.
	sharedlinkDescRevoked := sharedlinkFields[13].Descriptor()
	// sharedlink.DefaultRevoked holds the default value on creation for the revoked field.
	sharedlink.DefaultRevoked = sharedlinkDescRevoked.Default.(bool)
	// sharedlinkDescID is the schema descriptor for id field.
	sharedlinkDescID := sharedlinkFields[0].Descriptor()
	// sharedlink.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sharedlink.IDValidator = sharedlinkDescID.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
