// Code generated by ent, DO NOT EDIT.

package sharedlink

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sharedlink type in the database.
	Label = "shared_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldResourceType holds the string denoting the resource_type field in the database.
	FieldResourceType = "resource_type"
	// FieldResourceID holds the string denoting the resource_id field in the database.
	FieldResourceID = "resource_id"
	// FieldResourceName holds the string denoting the resource_name field in the database.
	FieldResourceName = "resource_name"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldEncryptedContent holds the string denoting the encrypted_content field in the database.
	FieldEncryptedContent = "encrypted_content"
	// FieldEncryptionNonce holds the string denoting the encryption_nonce field in the database.
	FieldEncryptionNonce = "encryption_nonce"
	// FieldRecipientEmail holds the string denoting the recipient_email field in the database.
	FieldRecipientEmail = "recipient_email"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldTemplateID holds the string denoting the template_id field in the database.
	FieldTemplateID = "template_id"
	// FieldViewed holds the string denoting the viewed field in the database.
	FieldViewed = "viewed"
	// FieldViewedAt holds the string denoting the viewed_at field in the database.
	FieldViewedAt = "viewed_at"
	// FieldViewedIP holds the string denoting the viewed_ip field in the database.
	FieldViewedIP = "viewed_ip"
	// FieldRevoked holds the string denoting the revoked field in the database.
	FieldRevoked = "revoked"
	// Table holds the table name of the sharedlink in the database.
	Table = "sharing_shared_links"
)

// Columns holds all SQL columns for sharedlink fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldResourceType,
	FieldResourceID,
	FieldResourceName,
	FieldToken,
	FieldEncryptedContent,
	FieldEncryptionNonce,
	FieldRecipientEmail,
	FieldMessage,
	FieldTemplateID,
	FieldViewed,
	FieldViewedAt,
	FieldViewedIP,
	FieldRevoked,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-sharing/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	ResourceIDValidator func(string) error
	// ResourceNameValidator is a validator for the "resource_name" field. It is called by the builders before save.
	ResourceNameValidator func(string) error
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// RecipientEmailValidator is a validator for the "recipient_email" field. It is called by the builders before save.
	RecipientEmailValidator func(string) error
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
	// TemplateIDValidator is a validator for the "template_id" field. It is called by the builders before save.
	TemplateIDValidator func(string) error
	// DefaultViewed holds the default value on creation for the "viewed" field.
	DefaultViewed bool
	// ViewedIPValidator is a validator for the "viewed_ip" field. It is called by the builders before save.
	ViewedIPValidator func(string) error
	// DefaultRevoked holds the default value on creation for the "revoked" field.
	DefaultRevoked bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// ResourceType defines the type for the "resource_type" enum field.
type ResourceType string

// ResourceType values.
const (
	ResourceTypeSECRET   ResourceType = "SECRET"
	ResourceTypeDOCUMENT ResourceType = "DOCUMENT"
)

func (rt ResourceType) String() string {
	return string(rt)
}

// ResourceTypeValidator is a validator for the "resource_type" field enum values. It is called by the builders before save.
func ResourceTypeValidator(rt ResourceType) error {
	switch rt {
	case ResourceTypeSECRET, ResourceTypeDOCUMENT:
		return nil
	default:
		return fmt.Errorf("sharedlink: invalid enum value for resource_type field: %q", rt)
	}
}

// OrderOption defines the ordering options for the SharedLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByResourceType orders the results by the resource_type field.
func ByResourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceType, opts...).ToFunc()
}

// ByResourceID orders the results by the resource_id field.
func ByResourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceID, opts...).ToFunc()
}

// ByResourceName orders the results by the resource_name field.
func ByResourceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResourceName, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByRecipientEmail orders the results by the recipient_email field.
func ByRecipientEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecipientEmail, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByTemplateID orders the results by the template_id field.
func ByTemplateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateID, opts...).ToFunc()
}

// ByViewed orders the results by the viewed field.
func ByViewed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewed, opts...).ToFunc()
}

// ByViewedAt orders the results by the viewed_at field.
func ByViewedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewedAt, opts...).ToFunc()
}

// ByViewedIP orders the results by the viewed_ip field.
func ByViewedIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewedIP, opts...).ToFunc()
}

// ByRevoked orders the results by the revoked field.
func ByRevoked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevoked, opts...).ToFunc()
}
