// Code generated by ent, DO NOT EDIT.

package sharedlink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldTenantID, v))
}

// ResourceID applies equality check predicate on the "resource_id" field. It's identical to ResourceIDEQ.
func ResourceID(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldResourceID, v))
}

// ResourceName applies equality check predicate on the "resource_name" field. It's identical to ResourceNameEQ.
func ResourceName(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldResourceName, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldToken, v))
}

// EncryptedContent applies equality check predicate on the "encrypted_content" field. It's identical to EncryptedContentEQ.
func EncryptedContent(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldEncryptedContent, v))
}

// EncryptionNonce applies equality check predicate on the "encryption_nonce" field. It's identical to EncryptionNonceEQ.
func EncryptionNonce(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldEncryptionNonce, v))
}

// RecipientEmail applies equality check predicate on the "recipient_email" field. It's identical to RecipientEmailEQ.
func RecipientEmail(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldRecipientEmail, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldMessage, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldTemplateID, v))
}

// Viewed applies equality check predicate on the "viewed" field. It's identical to ViewedEQ.
func Viewed(v bool) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldViewed, v))
}

// ViewedAt applies equality check predicate on the "viewed_at" field. It's identical to ViewedAtEQ.
func ViewedAt(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldViewedAt, v))
}

// ViewedIP applies equality check predicate on the "viewed_ip" field. It's identical to ViewedIPEQ.
func ViewedIP(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldViewedIP, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldRevoked, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldTenantID))
}

// ResourceTypeEQ applies the EQ predicate on the "resource_type" field.
func ResourceTypeEQ(v ResourceType) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldResourceType, v))
}

// ResourceTypeNEQ applies the NEQ predicate on the "resource_type" field.
func ResourceTypeNEQ(v ResourceType) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldResourceType, v))
}

// ResourceTypeIn applies the In predicate on the "resource_type" field.
func ResourceTypeIn(vs ...ResourceType) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldResourceType, vs...))
}

// ResourceTypeNotIn applies the NotIn predicate on the "resource_type" field.
func ResourceTypeNotIn(vs ...ResourceType) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldResourceType, vs...))
}

// ResourceIDEQ applies the EQ predicate on the "resource_id" field.
func ResourceIDEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldResourceID, v))
}

// ResourceIDNEQ applies the NEQ predicate on the "resource_id" field.
func ResourceIDNEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldResourceID, v))
}

// ResourceIDIn applies the In predicate on the "resource_id" field.
func ResourceIDIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldResourceID, vs...))
}

// ResourceIDNotIn applies the NotIn predicate on the "resource_id" field.
func ResourceIDNotIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldResourceID, vs...))
}

// ResourceIDGT applies the GT predicate on the "resource_id" field.
func ResourceIDGT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldResourceID, v))
}

// ResourceIDGTE applies the GTE predicate on the "resource_id" field.
func ResourceIDGTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldResourceID, v))
}

// ResourceIDLT applies the LT predicate on the "resource_id" field.
func ResourceIDLT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldResourceID, v))
}

// ResourceIDLTE applies the LTE predicate on the "resource_id" field.
func ResourceIDLTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldResourceID, v))
}

// ResourceIDContains applies the Contains predicate on the "resource_id" field.
func ResourceIDContains(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContains(FieldResourceID, v))
}

// ResourceIDHasPrefix applies the HasPrefix predicate on the "resource_id" field.
func ResourceIDHasPrefix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasPrefix(FieldResourceID, v))
}

// ResourceIDHasSuffix applies the HasSuffix predicate on the "resource_id" field.
func ResourceIDHasSuffix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasSuffix(FieldResourceID, v))
}

// ResourceIDEqualFold applies the EqualFold predicate on the "resource_id" field.
func ResourceIDEqualFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldResourceID, v))
}

// ResourceIDContainsFold applies the ContainsFold predicate on the "resource_id" field.
func ResourceIDContainsFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldResourceID, v))
}

// ResourceNameEQ applies the EQ predicate on the "resource_name" field.
func ResourceNameEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldResourceName, v))
}

// ResourceNameNEQ applies the NEQ predicate on the "resource_name" field.
func ResourceNameNEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldResourceName, v))
}

// ResourceNameIn applies the In predicate on the "resource_name" field.
func ResourceNameIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldResourceName, vs...))
}

// ResourceNameNotIn applies the NotIn predicate on the "resource_name" field.
func ResourceNameNotIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldResourceName, vs...))
}

// ResourceNameGT applies the GT predicate on the "resource_name" field.
func ResourceNameGT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldResourceName, v))
}

// ResourceNameGTE applies the GTE predicate on the "resource_name" field.
func ResourceNameGTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldResourceName, v))
}

// ResourceNameLT applies the LT predicate on the "resource_name" field.
func ResourceNameLT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldResourceName, v))
}

// ResourceNameLTE applies the LTE predicate on the "resource_name" field.
func ResourceNameLTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldResourceName, v))
}

// ResourceNameContains applies the Contains predicate on the "resource_name" field.
func ResourceNameContains(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContains(FieldResourceName, v))
}

// ResourceNameHasPrefix applies the HasPrefix predicate on the "resource_name" field.
func ResourceNameHasPrefix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasPrefix(FieldResourceName, v))
}

// ResourceNameHasSuffix applies the HasSuffix predicate on the "resource_name" field.
func ResourceNameHasSuffix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasSuffix(FieldResourceName, v))
}

// ResourceNameEqualFold applies the EqualFold predicate on the "resource_name" field.
func ResourceNameEqualFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldResourceName, v))
}

// ResourceNameContainsFold applies the ContainsFold predicate on the "resource_name" field.
func ResourceNameContainsFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldResourceName, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldToken, v))
}

// EncryptedContentEQ applies the EQ predicate on the "encrypted_content" field.
func EncryptedContentEQ(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldEncryptedContent, v))
}

// EncryptedContentNEQ applies the NEQ predicate on the "encrypted_content" field.
func EncryptedContentNEQ(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldEncryptedContent, v))
}

// EncryptedContentIn applies the In predicate on the "encrypted_content" field.
func EncryptedContentIn(vs ...[]byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldEncryptedContent, vs...))
}

// EncryptedContentNotIn applies the NotIn predicate on the "encrypted_content" field.
func EncryptedContentNotIn(vs ...[]byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldEncryptedContent, vs...))
}

// EncryptedContentGT applies the GT predicate on the "encrypted_content" field.
func EncryptedContentGT(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldEncryptedContent, v))
}

// EncryptedContentGTE applies the GTE predicate on the "encrypted_content" field.
func EncryptedContentGTE(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldEncryptedContent, v))
}

// EncryptedContentLT applies the LT predicate on the "encrypted_content" field.
func EncryptedContentLT(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldEncryptedContent, v))
}

// EncryptedContentLTE applies the LTE predicate on the "encrypted_content" field.
func EncryptedContentLTE(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldEncryptedContent, v))
}

// EncryptedContentIsNil applies the IsNil predicate on the "encrypted_content" field.
func EncryptedContentIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldEncryptedContent))
}

// EncryptedContentNotNil applies the NotNil predicate on the "encrypted_content" field.
func EncryptedContentNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldEncryptedContent))
}

// EncryptionNonceEQ applies the EQ predicate on the "encryption_nonce" field.
func EncryptionNonceEQ(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldEncryptionNonce, v))
}

// EncryptionNonceNEQ applies the NEQ predicate on the "encryption_nonce" field.
func EncryptionNonceNEQ(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldEncryptionNonce, v))
}

// EncryptionNonceIn applies the In predicate on the "encryption_nonce" field.
func EncryptionNonceIn(vs ...[]byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldEncryptionNonce, vs...))
}

// EncryptionNonceNotIn applies the NotIn predicate on the "encryption_nonce" field.
func EncryptionNonceNotIn(vs ...[]byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldEncryptionNonce, vs...))
}

// EncryptionNonceGT applies the GT predicate on the "encryption_nonce" field.
func EncryptionNonceGT(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldEncryptionNonce, v))
}

// EncryptionNonceGTE applies the GTE predicate on the "encryption_nonce" field.
func EncryptionNonceGTE(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldEncryptionNonce, v))
}

// EncryptionNonceLT applies the LT predicate on the "encryption_nonce" field.
func EncryptionNonceLT(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldEncryptionNonce, v))
}

// EncryptionNonceLTE applies the LTE predicate on the "encryption_nonce" field.
func EncryptionNonceLTE(v []byte) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldEncryptionNonce, v))
}

// EncryptionNonceIsNil applies the IsNil predicate on the "encryption_nonce" field.
func EncryptionNonceIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldEncryptionNonce))
}

// EncryptionNonceNotNil applies the NotNil predicate on the "encryption_nonce" field.
func EncryptionNonceNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldEncryptionNonce))
}

// RecipientEmailEQ applies the EQ predicate on the "recipient_email" field.
func RecipientEmailEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldRecipientEmail, v))
}

// RecipientEmailNEQ applies the NEQ predicate on the "recipient_email" field.
func RecipientEmailNEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldRecipientEmail, v))
}

// RecipientEmailIn applies the In predicate on the "recipient_email" field.
func RecipientEmailIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldRecipientEmail, vs...))
}

// RecipientEmailNotIn applies the NotIn predicate on the "recipient_email" field.
func RecipientEmailNotIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldRecipientEmail, vs...))
}

// RecipientEmailGT applies the GT predicate on the "recipient_email" field.
func RecipientEmailGT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldRecipientEmail, v))
}

// RecipientEmailGTE applies the GTE predicate on the "recipient_email" field.
func RecipientEmailGTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldRecipientEmail, v))
}

// RecipientEmailLT applies the LT predicate on the "recipient_email" field.
func RecipientEmailLT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldRecipientEmail, v))
}

// RecipientEmailLTE applies the LTE predicate on the "recipient_email" field.
func RecipientEmailLTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldRecipientEmail, v))
}

// RecipientEmailContains applies the Contains predicate on the "recipient_email" field.
func RecipientEmailContains(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContains(FieldRecipientEmail, v))
}

// RecipientEmailHasPrefix applies the HasPrefix predicate on the "recipient_email" field.
func RecipientEmailHasPrefix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasPrefix(FieldRecipientEmail, v))
}

// RecipientEmailHasSuffix applies the HasSuffix predicate on the "recipient_email" field.
func RecipientEmailHasSuffix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasSuffix(FieldRecipientEmail, v))
}

// RecipientEmailEqualFold applies the EqualFold predicate on the "recipient_email" field.
func RecipientEmailEqualFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldRecipientEmail, v))
}

// RecipientEmailContainsFold applies the ContainsFold predicate on the "recipient_email" field.
func RecipientEmailContainsFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldRecipientEmail, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldMessage, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDContains applies the Contains predicate on the "template_id" field.
func TemplateIDContains(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContains(FieldTemplateID, v))
}

// TemplateIDHasPrefix applies the HasPrefix predicate on the "template_id" field.
func TemplateIDHasPrefix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasPrefix(FieldTemplateID, v))
}

// TemplateIDHasSuffix applies the HasSuffix predicate on the "template_id" field.
func TemplateIDHasSuffix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasSuffix(FieldTemplateID, v))
}

// TemplateIDIsNil applies the IsNil predicate on the "template_id" field.
func TemplateIDIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldTemplateID))
}

// TemplateIDNotNil applies the NotNil predicate on the "template_id" field.
func TemplateIDNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldTemplateID))
}

// TemplateIDEqualFold applies the EqualFold predicate on the "template_id" field.
func TemplateIDEqualFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldTemplateID, v))
}

// TemplateIDContainsFold applies the ContainsFold predicate on the "template_id" field.
func TemplateIDContainsFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldTemplateID, v))
}

// ViewedEQ applies the EQ predicate on the "viewed" field.
func ViewedEQ(v bool) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldViewed, v))
}

// ViewedNEQ applies the NEQ predicate on the "viewed" field.
func ViewedNEQ(v bool) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldViewed, v))
}

// ViewedAtEQ applies the EQ predicate on the "viewed_at" field.
func ViewedAtEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldViewedAt, v))
}

// ViewedAtNEQ applies the NEQ predicate on the "viewed_at" field.
func ViewedAtNEQ(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldViewedAt, v))
}

// ViewedAtIn applies the In predicate on the "viewed_at" field.
func ViewedAtIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldViewedAt, vs...))
}

// ViewedAtNotIn applies the NotIn predicate on the "viewed_at" field.
func ViewedAtNotIn(vs ...time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldViewedAt, vs...))
}

// ViewedAtGT applies the GT predicate on the "viewed_at" field.
func ViewedAtGT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldViewedAt, v))
}

// ViewedAtGTE applies the GTE predicate on the "viewed_at" field.
func ViewedAtGTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldViewedAt, v))
}

// ViewedAtLT applies the LT predicate on the "viewed_at" field.
func ViewedAtLT(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldViewedAt, v))
}

// ViewedAtLTE applies the LTE predicate on the "viewed_at" field.
func ViewedAtLTE(v time.Time) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldViewedAt, v))
}

// ViewedAtIsNil applies the IsNil predicate on the "viewed_at" field.
func ViewedAtIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldViewedAt))
}

// ViewedAtNotNil applies the NotNil predicate on the "viewed_at" field.
func ViewedAtNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldViewedAt))
}

// ViewedIPEQ applies the EQ predicate on the "viewed_ip" field.
func ViewedIPEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldViewedIP, v))
}

// ViewedIPNEQ applies the NEQ predicate on the "viewed_ip" field.
func ViewedIPNEQ(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldViewedIP, v))
}

// ViewedIPIn applies the In predicate on the "viewed_ip" field.
func ViewedIPIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIn(FieldViewedIP, vs...))
}

// ViewedIPNotIn applies the NotIn predicate on the "viewed_ip" field.
func ViewedIPNotIn(vs ...string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotIn(FieldViewedIP, vs...))
}

// ViewedIPGT applies the GT predicate on the "viewed_ip" field.
func ViewedIPGT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGT(FieldViewedIP, v))
}

// ViewedIPGTE applies the GTE predicate on the "viewed_ip" field.
func ViewedIPGTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldGTE(FieldViewedIP, v))
}

// ViewedIPLT applies the LT predicate on the "viewed_ip" field.
func ViewedIPLT(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLT(FieldViewedIP, v))
}

// ViewedIPLTE applies the LTE predicate on the "viewed_ip" field.
func ViewedIPLTE(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldLTE(FieldViewedIP, v))
}

// ViewedIPContains applies the Contains predicate on the "viewed_ip" field.
func ViewedIPContains(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContains(FieldViewedIP, v))
}

// ViewedIPHasPrefix applies the HasPrefix predicate on the "viewed_ip" field.
func ViewedIPHasPrefix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasPrefix(FieldViewedIP, v))
}

// ViewedIPHasSuffix applies the HasSuffix predicate on the "viewed_ip" field.
func ViewedIPHasSuffix(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldHasSuffix(FieldViewedIP, v))
}

// ViewedIPIsNil applies the IsNil predicate on the "viewed_ip" field.
func ViewedIPIsNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldIsNull(FieldViewedIP))
}

// ViewedIPNotNil applies the NotNil predicate on the "viewed_ip" field.
func ViewedIPNotNil() predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNotNull(FieldViewedIP))
}

// ViewedIPEqualFold applies the EqualFold predicate on the "viewed_ip" field.
func ViewedIPEqualFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEqualFold(FieldViewedIP, v))
}

// ViewedIPContainsFold applies the ContainsFold predicate on the "viewed_ip" field.
func ViewedIPContainsFold(v string) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldContainsFold(FieldViewedIP, v))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.SharedLink {
	return predicate.SharedLink(sql.FieldNEQ(FieldRevoked, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharedLink) predicate.SharedLink {
	return predicate.SharedLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharedLink) predicate.SharedLink {
	return predicate.SharedLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharedLink) predicate.SharedLink {
	return predicate.SharedLink(sql.NotPredicates(p))
}
