// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/emailtemplate"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharedlink"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharepolicy"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// EmailTemplate is the client for interacting with the EmailTemplate builders.
	EmailTemplate *EmailTemplateClient
	// SharePolicy is the client for interacting with the SharePolicy builders.
	SharePolicy *SharePolicyClient
	// SharedLink is the client for interacting with the SharedLink builders.
	SharedLink *SharedLinkClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.EmailTemplate = NewEmailTemplateClient(c.config)
	c.SharePolicy = NewSharePolicyClient(c.config)
	c.SharedLink = NewSharedLinkClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		EmailTemplate: NewEmailTemplateClient(cfg),
		SharePolicy:   NewSharePolicyClient(cfg),
		SharedLink:    NewSharedLinkClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		EmailTemplate: NewEmailTemplateClient(cfg),
		SharePolicy:   NewSharePolicyClient(cfg),
		SharedLink:    NewSharedLinkClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		EmailTemplate.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.EmailTemplate.Use(hooks...)
	c.SharePolicy.Use(hooks...)
	c.SharedLink.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.EmailTemplate.Intercept(interceptors...)
	c.SharePolicy.Intercept(interceptors...)
	c.SharedLink.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *EmailTemplateMutation:
		return c.EmailTemplate.mutate(ctx, m)
	case *SharePolicyMutation:
		return c.SharePolicy.mutate(ctx, m)
	case *SharedLinkMutation:
		return c.SharedLink.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// EmailTemplateClient is a client for the EmailTemplate schema.
type EmailTemplateClient struct {
	config
}

// NewEmailTemplateClient returns a client for the EmailTemplate from the given config.
func NewEmailTemplateClient(c config) *EmailTemplateClient {
	return &EmailTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `emailtemplate.Hooks(f(g(h())))`.
func (c *EmailTemplateClient) Use(hooks ...Hook) {
	c.hooks.EmailTemplate = append(c.hooks.EmailTemplate, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `emailtemplate.Intercept(f(g(h())))`.
func (c *EmailTemplateClient) Intercept(interceptors ...Interceptor) {
	c.inters.EmailTemplate = append(c.inters.EmailTemplate, interceptors...)
}

// Create returns a builder for creating a EmailTemplate entity.
func (c *EmailTemplateClient) Create() *EmailTemplateCreate {
	mutation := newEmailTemplateMutation(c.config, OpCreate)
	return &EmailTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of EmailTemplate entities.
func (c *EmailTemplateClient) CreateBulk(builders ...*EmailTemplateCreate) *EmailTemplateCreateBulk {
	return &EmailTemplateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmailTemplateClient) MapCreateBulk(slice any, setFunc func(*EmailTemplateCreate, int)) *EmailTemplateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmailTemplateCreateBulk{err: fmt.Errorf("calling to EmailTemplateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmailTemplateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmailTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for EmailTemplate.
func (c *EmailTemplateClient) Update() *EmailTemplateUpdate {
	mutation := newEmailTemplateMutation(c.config, OpUpdate)
	return &EmailTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmailTemplateClient) UpdateOne(_m *EmailTemplate) *EmailTemplateUpdateOne {
	mutation := newEmailTemplateMutation(c.config, OpUpdateOne, withEmailTemplate(_m))
	return &EmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmailTemplateClient) UpdateOneID(id string) *EmailTemplateUpdateOne {
	mutation := newEmailTemplateMutation(c.config, OpUpdateOne, withEmailTemplateID(id))
	return &EmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for EmailTemplate.
func (c *EmailTemplateClient) Delete() *EmailTemplateDelete {
	mutation := newEmailTemplateMutation(c.config, OpDelete)
	return &EmailTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmailTemplateClient) DeleteOne(_m *EmailTemplate) *EmailTemplateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmailTemplateClient) DeleteOneID(id string) *EmailTemplateDeleteOne {
	builder := c.Delete().Where(emailtemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmailTemplateDeleteOne{builder}
}

// Query returns a query builder for EmailTemplate.
func (c *EmailTemplateClient) Query() *EmailTemplateQuery {
	return &EmailTemplateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmailTemplate},
		inters: c.Interceptors(),
	}
}

// Get returns a EmailTemplate entity by its id.
func (c *EmailTemplateClient) Get(ctx context.Context, id string) (*EmailTemplate, error) {
	return c.Query().Where(emailtemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmailTemplateClient) GetX(ctx context.Context, id string) *EmailTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EmailTemplateClient) Hooks() []Hook {
	hooks := c.hooks.EmailTemplate
	return append(hooks[:len(hooks):len(hooks)], emailtemplate.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *EmailTemplateClient) Interceptors() []Interceptor {
	return c.inters.EmailTemplate
}

func (c *EmailTemplateClient) mutate(ctx context.Context, m *EmailTemplateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmailTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmailTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmailTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmailTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown EmailTemplate mutation op: %q", m.Op())
	}
}

// SharePolicyClient is a client for the SharePolicy schema.
type SharePolicyClient struct {
	config
}

// NewSharePolicyClient returns a client for the SharePolicy from the given config.
func NewSharePolicyClient(c config) *SharePolicyClient {
	return &SharePolicyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sharepolicy.Hooks(f(g(h())))`.
func (c *SharePolicyClient) Use(hooks ...Hook) {
	c.hooks.SharePolicy = append(c.hooks.SharePolicy, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sharepolicy.Intercept(f(g(h())))`.
func (c *SharePolicyClient) Intercept(interceptors ...Interceptor) {
	c.inters.SharePolicy = append(c.inters.SharePolicy, interceptors...)
}

// Create returns a builder for creating a SharePolicy entity.
func (c *SharePolicyClient) Create() *SharePolicyCreate {
	mutation := newSharePolicyMutation(c.config, OpCreate)
	return &SharePolicyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SharePolicy entities.
func (c *SharePolicyClient) CreateBulk(builders ...*SharePolicyCreate) *SharePolicyCreateBulk {
	return &SharePolicyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SharePolicyClient) MapCreateBulk(slice any, setFunc func(*SharePolicyCreate, int)) *SharePolicyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SharePolicyCreateBulk{err: fmt.Errorf("calling to SharePolicyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SharePolicyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SharePolicyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SharePolicy.
func (c *SharePolicyClient) Update() *SharePolicyUpdate {
	mutation := newSharePolicyMutation(c.config, OpUpdate)
	return &SharePolicyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SharePolicyClient) UpdateOne(_m *SharePolicy) *SharePolicyUpdateOne {
	mutation := newSharePolicyMutation(c.config, OpUpdateOne, withSharePolicy(_m))
	return &SharePolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SharePolicyClient) UpdateOneID(id string) *SharePolicyUpdateOne {
	mutation := newSharePolicyMutation(c.config, OpUpdateOne, withSharePolicyID(id))
	return &SharePolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SharePolicy.
func (c *SharePolicyClient) Delete() *SharePolicyDelete {
	mutation := newSharePolicyMutation(c.config, OpDelete)
	return &SharePolicyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SharePolicyClient) DeleteOne(_m *SharePolicy) *SharePolicyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SharePolicyClient) DeleteOneID(id string) *SharePolicyDeleteOne {
	builder := c.Delete().Where(sharepolicy.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SharePolicyDeleteOne{builder}
}

// Query returns a query builder for SharePolicy.
func (c *SharePolicyClient) Query() *SharePolicyQuery {
	return &SharePolicyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSharePolicy},
		inters: c.Interceptors(),
	}
}

// Get returns a SharePolicy entity by its id.
func (c *SharePolicyClient) Get(ctx context.Context, id string) (*SharePolicy, error) {
	return c.Query().Where(sharepolicy.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SharePolicyClient) GetX(ctx context.Context, id string) *SharePolicy {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SharePolicyClient) Hooks() []Hook {
	hooks := c.hooks.SharePolicy
	return append(hooks[:len(hooks):len(hooks)], sharepolicy.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *SharePolicyClient) Interceptors() []Interceptor {
	return c.inters.SharePolicy
}

func (c *SharePolicyClient) mutate(ctx context.Context, m *SharePolicyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SharePolicyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SharePolicyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SharePolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SharePolicyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SharePolicy mutation op: %q", m.Op())
	}
}

// SharedLinkClient is a client for the SharedLink schema.
type SharedLinkClient struct {
	config
}

// NewSharedLinkClient returns a client for the SharedLink from the given config.
func NewSharedLinkClient(c config) *SharedLinkClient {
	return &SharedLinkClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sharedlink.Hooks(f(g(h())))`.
func (c *SharedLinkClient) Use(hooks ...Hook) {
	c.hooks.SharedLink = append(c.hooks.SharedLink, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sharedlink.Intercept(f(g(h())))`.
func (c *SharedLinkClient) Intercept(interceptors ...Interceptor) {
	c.inters.SharedLink = append(c.inters.SharedLink, interceptors...)
}

// Create returns a builder for creating a SharedLink entity.
func (c *SharedLinkClient) Create() *SharedLinkCreate {
	mutation := newSharedLinkMutation(c.config, OpCreate)
	return &SharedLinkCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SharedLink entities.
func (c *SharedLinkClient) CreateBulk(builders ...*SharedLinkCreate) *SharedLinkCreateBulk {
	return &SharedLinkCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SharedLinkClient) MapCreateBulk(slice any, setFunc func(*SharedLinkCreate, int)) *SharedLinkCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SharedLinkCreateBulk{err: fmt.Errorf("calling to SharedLinkClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SharedLinkCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SharedLinkCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SharedLink.
func (c *SharedLinkClient) Update() *SharedLinkUpdate {
	mutation := newSharedLinkMutation(c.config, OpUpdate)
	return &SharedLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SharedLinkClient) UpdateOne(_m *SharedLink) *SharedLinkUpdateOne {
	mutation := newSharedLinkMutation(c.config, OpUpdateOne, withSharedLink(_m))
	return &SharedLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SharedLinkClient) UpdateOneID(id string) *SharedLinkUpdateOne {
	mutation := newSharedLinkMutation(c.config, OpUpdateOne, withSharedLinkID(id))
	return &SharedLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SharedLink.
func (c *SharedLinkClient) Delete() *SharedLinkDelete {
	mutation := newSharedLinkMutation(c.config, OpDelete)
	return &SharedLinkDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SharedLinkClient) DeleteOne(_m *SharedLink) *SharedLinkDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SharedLinkClient) DeleteOneID(id string) *SharedLinkDeleteOne {
	builder := c.Delete().Where(sharedlink.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SharedLinkDeleteOne{builder}
}

// Query returns a query builder for SharedLink.
func (c *SharedLinkClient) Query() *SharedLinkQuery {
	return &SharedLinkQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSharedLink},
		inters: c.Interceptors(),
	}
}

// Get returns a SharedLink entity by its id.
func (c *SharedLinkClient) Get(ctx context.Context, id string) (*SharedLink, error) {
	return c.Query().Where(sharedlink.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SharedLinkClient) GetX(ctx context.Context, id string) *SharedLink {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SharedLinkClient) Hooks() []Hook {
	hooks := c.hooks.SharedLink
	return append(hooks[:len(hooks):len(hooks)], sharedlink.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *SharedLinkClient) Interceptors() []Interceptor {
	return c.inters.SharedLink
}

func (c *SharedLinkClient) mutate(ctx context.Context, m *SharedLinkMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SharedLinkCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SharedLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SharedLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SharedLinkDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SharedLink mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		EmailTemplate, SharePolicy, SharedLink []ent.Hook
	}
	inters struct {
		EmailTemplate, SharePolicy, SharedLink []ent.Interceptor
	}
)
