// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/emailtemplate"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/predicate"
)

// EmailTemplateUpdate is the builder for updating EmailTemplate entities.
type EmailTemplateUpdate struct {
	config
	hooks     []Hook
	mutation  *EmailTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the EmailTemplateUpdate builder.
func (_u *EmailTemplateUpdate) Where(ps ...predicate.EmailTemplate) *EmailTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *EmailTemplateUpdate) SetCreateBy(v uint32) *EmailTemplateUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableCreateBy(v *uint32) *EmailTemplateUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *EmailTemplateUpdate) AddCreateBy(v int32) *EmailTemplateUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *EmailTemplateUpdate) ClearCreateBy() *EmailTemplateUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *EmailTemplateUpdate) SetUpdateBy(v uint32) *EmailTemplateUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableUpdateBy(v *uint32) *EmailTemplateUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *EmailTemplateUpdate) AddUpdateBy(v int32) *EmailTemplateUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *EmailTemplateUpdate) ClearUpdateBy() *EmailTemplateUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *EmailTemplateUpdate) SetUpdateTime(v time.Time) *EmailTemplateUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableUpdateTime(v *time.Time) *EmailTemplateUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *EmailTemplateUpdate) ClearUpdateTime() *EmailTemplateUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *EmailTemplateUpdate) SetDeleteTime(v time.Time) *EmailTemplateUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableDeleteTime(v *time.Time) *EmailTemplateUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *EmailTemplateUpdate) ClearDeleteTime() *EmailTemplateUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *EmailTemplateUpdate) SetName(v string) *EmailTemplateUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableName(v *string) *EmailTemplateUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *EmailTemplateUpdate) SetSubject(v string) *EmailTemplateUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableSubject(v *string) *EmailTemplateUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetHTMLBody sets the "html_body" field.
func (_u *EmailTemplateUpdate) SetHTMLBody(v string) *EmailTemplateUpdate {
	_u.mutation.SetHTMLBody(v)
	return _u
}

// SetNillableHTMLBody sets the "html_body" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableHTMLBody(v *string) *EmailTemplateUpdate {
	if v != nil {
		_u.SetHTMLBody(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *EmailTemplateUpdate) SetIsDefault(v bool) *EmailTemplateUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *EmailTemplateUpdate) SetNillableIsDefault(v *bool) *EmailTemplateUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the EmailTemplateMutation object of the builder.
func (_u *EmailTemplateUpdate) Mutation() *EmailTemplateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailTemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailTemplateUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := emailtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := emailtemplate.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTMLBody(); ok {
		if err := emailtemplate.HTMLBodyValidator(v); err != nil {
			return &ValidationError{Name: "html_body", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.html_body": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EmailTemplateUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmailTemplateUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EmailTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailtemplate.Table, emailtemplate.Columns, sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(emailtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(emailtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(emailtemplate.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(emailtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(emailtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(emailtemplate.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(emailtemplate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(emailtemplate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(emailtemplate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(emailtemplate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(emailtemplate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(emailtemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(emailtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(emailtemplate.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTMLBody(); ok {
		_spec.SetField(emailtemplate.FieldHTMLBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(emailtemplate.FieldIsDefault, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailTemplateUpdateOne is the builder for updating a single EmailTemplate entity.
type EmailTemplateUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *EmailTemplateMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *EmailTemplateUpdateOne) SetCreateBy(v uint32) *EmailTemplateUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableCreateBy(v *uint32) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *EmailTemplateUpdateOne) AddCreateBy(v int32) *EmailTemplateUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *EmailTemplateUpdateOne) ClearCreateBy() *EmailTemplateUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *EmailTemplateUpdateOne) SetUpdateBy(v uint32) *EmailTemplateUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableUpdateBy(v *uint32) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *EmailTemplateUpdateOne) AddUpdateBy(v int32) *EmailTemplateUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *EmailTemplateUpdateOne) ClearUpdateBy() *EmailTemplateUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *EmailTemplateUpdateOne) SetUpdateTime(v time.Time) *EmailTemplateUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableUpdateTime(v *time.Time) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *EmailTemplateUpdateOne) ClearUpdateTime() *EmailTemplateUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *EmailTemplateUpdateOne) SetDeleteTime(v time.Time) *EmailTemplateUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableDeleteTime(v *time.Time) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *EmailTemplateUpdateOne) ClearDeleteTime() *EmailTemplateUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *EmailTemplateUpdateOne) SetName(v string) *EmailTemplateUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableName(v *string) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *EmailTemplateUpdateOne) SetSubject(v string) *EmailTemplateUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableSubject(v *string) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetHTMLBody sets the "html_body" field.
func (_u *EmailTemplateUpdateOne) SetHTMLBody(v string) *EmailTemplateUpdateOne {
	_u.mutation.SetHTMLBody(v)
	return _u
}

// SetNillableHTMLBody sets the "html_body" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableHTMLBody(v *string) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetHTMLBody(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *EmailTemplateUpdateOne) SetIsDefault(v bool) *EmailTemplateUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *EmailTemplateUpdateOne) SetNillableIsDefault(v *bool) *EmailTemplateUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// Mutation returns the EmailTemplateMutation object of the builder.
func (_u *EmailTemplateUpdateOne) Mutation() *EmailTemplateMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailTemplateUpdate builder.
func (_u *EmailTemplateUpdateOne) Where(ps ...predicate.EmailTemplate) *EmailTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailTemplateUpdateOne) Select(field string, fields ...string) *EmailTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailTemplate entity.
func (_u *EmailTemplateUpdateOne) Save(ctx context.Context) (*EmailTemplate, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailTemplateUpdateOne) SaveX(ctx context.Context) *EmailTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := emailtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := emailtemplate.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HTMLBody(); ok {
		if err := emailtemplate.HTMLBodyValidator(v); err != nil {
			return &ValidationError{Name: "html_body", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.html_body": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *EmailTemplateUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *EmailTemplateUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *EmailTemplateUpdateOne) sqlSave(ctx context.Context) (_node *EmailTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailtemplate.Table, emailtemplate.Columns, sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailtemplate.FieldID)
		for _, f := range fields {
			if !emailtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(emailtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(emailtemplate.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(emailtemplate.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(emailtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(emailtemplate.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(emailtemplate.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(emailtemplate.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(emailtemplate.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(emailtemplate.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(emailtemplate.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(emailtemplate.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(emailtemplate.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(emailtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(emailtemplate.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.HTMLBody(); ok {
		_spec.SetField(emailtemplate.FieldHTMLBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(emailtemplate.FieldIsDefault, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &EmailTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
