// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/emailtemplate"
)

// EmailTemplateCreate is the builder for creating a EmailTemplate entity.
type EmailTemplateCreate struct {
	config
	mutation *EmailTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *EmailTemplateCreate) SetCreateBy(v uint32) *EmailTemplateCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableCreateBy(v *uint32) *EmailTemplateCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *EmailTemplateCreate) SetUpdateBy(v uint32) *EmailTemplateCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableUpdateBy(v *uint32) *EmailTemplateCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *EmailTemplateCreate) SetCreateTime(v time.Time) *EmailTemplateCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableCreateTime(v *time.Time) *EmailTemplateCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *EmailTemplateCreate) SetUpdateTime(v time.Time) *EmailTemplateCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableUpdateTime(v *time.Time) *EmailTemplateCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *EmailTemplateCreate) SetDeleteTime(v time.Time) *EmailTemplateCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableDeleteTime(v *time.Time) *EmailTemplateCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *EmailTemplateCreate) SetTenantID(v uint32) *EmailTemplateCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableTenantID(v *uint32) *EmailTemplateCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *EmailTemplateCreate) SetName(v string) *EmailTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *EmailTemplateCreate) SetSubject(v string) *EmailTemplateCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetHTMLBody sets the "html_body" field.
func (_c *EmailTemplateCreate) SetHTMLBody(v string) *EmailTemplateCreate {
	_c.mutation.SetHTMLBody(v)
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *EmailTemplateCreate) SetIsDefault(v bool) *EmailTemplateCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *EmailTemplateCreate) SetNillableIsDefault(v *bool) *EmailTemplateCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EmailTemplateCreate) SetID(v string) *EmailTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EmailTemplateMutation object of the builder.
func (_c *EmailTemplateCreate) Mutation() *EmailTemplateMutation {
	return _c.mutation
}

// Save creates the EmailTemplate in the database.
func (_c *EmailTemplateCreate) Save(ctx context.Context) (*EmailTemplate, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailTemplateCreate) SaveX(ctx context.Context) *EmailTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailTemplateCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := emailtemplate.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := emailtemplate.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailTemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "EmailTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := emailtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "EmailTemplate.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := emailtemplate.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HTMLBody(); !ok {
		return &ValidationError{Name: "html_body", err: errors.New(`ent: missing required field "EmailTemplate.html_body"`)}
	}
	if v, ok := _c.mutation.HTMLBody(); ok {
		if err := emailtemplate.HTMLBodyValidator(v); err != nil {
			return &ValidationError{Name: "html_body", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.html_body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "EmailTemplate.is_default"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := emailtemplate.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "EmailTemplate.id": %w`, err)}
		}
	}
	return nil
}

func (_c *EmailTemplateCreate) sqlSave(ctx context.Context) (*EmailTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EmailTemplate.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailTemplateCreate) createSpec() (*EmailTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailtemplate.Table, sqlgraph.NewFieldSpec(emailtemplate.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(emailtemplate.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(emailtemplate.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(emailtemplate.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(emailtemplate.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(emailtemplate.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(emailtemplate.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(emailtemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(emailtemplate.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.HTMLBody(); ok {
		_spec.SetField(emailtemplate.FieldHTMLBody, field.TypeString, value)
		_node.HTMLBody = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(emailtemplate.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailTemplate.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailTemplateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailTemplateCreate) OnConflict(opts ...sql.ConflictOption) *EmailTemplateUpsertOne {
	_c.conflict = opts
	return &EmailTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailTemplateCreate) OnConflictColumns(columns ...string) *EmailTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailTemplateUpsertOne{
		create: _c,
	}
}

type (
	// EmailTemplateUpsertOne is the builder for "upsert"-ing
	//  one EmailTemplate node.
	EmailTemplateUpsertOne struct {
		create *EmailTemplateCreate
	}

	// EmailTemplateUpsert is the "OnConflict" setter.
	EmailTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *EmailTemplateUpsert) SetCreateBy(v uint32) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateCreateBy() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *EmailTemplateUpsert) AddCreateBy(v uint32) *EmailTemplateUpsert {
	u.Add(emailtemplate.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *EmailTemplateUpsert) ClearCreateBy() *EmailTemplateUpsert {
	u.SetNull(emailtemplate.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *EmailTemplateUpsert) SetUpdateBy(v uint32) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateUpdateBy() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *EmailTemplateUpsert) AddUpdateBy(v uint32) *EmailTemplateUpsert {
	u.Add(emailtemplate.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *EmailTemplateUpsert) ClearUpdateBy() *EmailTemplateUpsert {
	u.SetNull(emailtemplate.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *EmailTemplateUpsert) SetUpdateTime(v time.Time) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateUpdateTime() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *EmailTemplateUpsert) ClearUpdateTime() *EmailTemplateUpsert {
	u.SetNull(emailtemplate.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *EmailTemplateUpsert) SetDeleteTime(v time.Time) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateDeleteTime() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *EmailTemplateUpsert) ClearDeleteTime() *EmailTemplateUpsert {
	u.SetNull(emailtemplate.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *EmailTemplateUpsert) SetName(v string) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateName() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldName)
	return u
}

// SetSubject sets the "subject" field.
func (u *EmailTemplateUpsert) SetSubject(v string) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateSubject() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldSubject)
	return u
}

// SetHTMLBody sets the "html_body" field.
func (u *EmailTemplateUpsert) SetHTMLBody(v string) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldHTMLBody, v)
	return u
}

// UpdateHTMLBody sets the "html_body" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateHTMLBody() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldHTMLBody)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *EmailTemplateUpsert) SetIsDefault(v bool) *EmailTemplateUpsert {
	u.Set(emailtemplate.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *EmailTemplateUpsert) UpdateIsDefault() *EmailTemplateUpsert {
	u.SetExcluded(emailtemplate.FieldIsDefault)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emailtemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailTemplateUpsertOne) UpdateNewValues() *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(emailtemplate.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(emailtemplate.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(emailtemplate.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EmailTemplateUpsertOne) Ignore() *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailTemplateUpsertOne) DoNothing() *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailTemplateCreate.OnConflict
// documentation for more info.
func (u *EmailTemplateUpsertOne) Update(set func(*EmailTemplateUpsert)) *EmailTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *EmailTemplateUpsertOne) SetCreateBy(v uint32) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *EmailTemplateUpsertOne) AddCreateBy(v uint32) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateCreateBy() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *EmailTemplateUpsertOne) ClearCreateBy() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *EmailTemplateUpsertOne) SetUpdateBy(v uint32) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *EmailTemplateUpsertOne) AddUpdateBy(v uint32) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateUpdateBy() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *EmailTemplateUpsertOne) ClearUpdateBy() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *EmailTemplateUpsertOne) SetUpdateTime(v time.Time) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateUpdateTime() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *EmailTemplateUpsertOne) ClearUpdateTime() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *EmailTemplateUpsertOne) SetDeleteTime(v time.Time) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateDeleteTime() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *EmailTemplateUpsertOne) ClearDeleteTime() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *EmailTemplateUpsertOne) SetName(v string) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateName() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateName()
	})
}

// SetSubject sets the "subject" field.
func (u *EmailTemplateUpsertOne) SetSubject(v string) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateSubject() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateSubject()
	})
}

// SetHTMLBody sets the "html_body" field.
func (u *EmailTemplateUpsertOne) SetHTMLBody(v string) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetHTMLBody(v)
	})
}

// UpdateHTMLBody sets the "html_body" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateHTMLBody() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateHTMLBody()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *EmailTemplateUpsertOne) SetIsDefault(v bool) *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *EmailTemplateUpsertOne) UpdateIsDefault() *EmailTemplateUpsertOne {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateIsDefault()
	})
}

// Exec executes the query.
func (u *EmailTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EmailTemplateUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EmailTemplateUpsertOne.ID is not supported by MySQL driver. Use EmailTemplateUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EmailTemplateUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EmailTemplateCreateBulk is the builder for creating many EmailTemplate entities in bulk.
type EmailTemplateCreateBulk struct {
	config
	err      error
	builders []*EmailTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the EmailTemplate entities in the database.
func (_c *EmailTemplateCreateBulk) Save(ctx context.Context) ([]*EmailTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailTemplateCreateBulk) SaveX(ctx context.Context) []*EmailTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.EmailTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EmailTemplateUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *EmailTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *EmailTemplateUpsertBulk {
	_c.conflict = opts
	return &EmailTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EmailTemplateCreateBulk) OnConflictColumns(columns ...string) *EmailTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EmailTemplateUpsertBulk{
		create: _c,
	}
}

// EmailTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of EmailTemplate nodes.
type EmailTemplateUpsertBulk struct {
	create *EmailTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(emailtemplate.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EmailTemplateUpsertBulk) UpdateNewValues() *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(emailtemplate.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(emailtemplate.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(emailtemplate.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.EmailTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EmailTemplateUpsertBulk) Ignore() *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EmailTemplateUpsertBulk) DoNothing() *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EmailTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *EmailTemplateUpsertBulk) Update(set func(*EmailTemplateUpsert)) *EmailTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EmailTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *EmailTemplateUpsertBulk) SetCreateBy(v uint32) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *EmailTemplateUpsertBulk) AddCreateBy(v uint32) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateCreateBy() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *EmailTemplateUpsertBulk) ClearCreateBy() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *EmailTemplateUpsertBulk) SetUpdateBy(v uint32) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *EmailTemplateUpsertBulk) AddUpdateBy(v uint32) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateUpdateBy() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *EmailTemplateUpsertBulk) ClearUpdateBy() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *EmailTemplateUpsertBulk) SetUpdateTime(v time.Time) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateUpdateTime() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *EmailTemplateUpsertBulk) ClearUpdateTime() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *EmailTemplateUpsertBulk) SetDeleteTime(v time.Time) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateDeleteTime() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *EmailTemplateUpsertBulk) ClearDeleteTime() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *EmailTemplateUpsertBulk) SetName(v string) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateName() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateName()
	})
}

// SetSubject sets the "subject" field.
func (u *EmailTemplateUpsertBulk) SetSubject(v string) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateSubject() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateSubject()
	})
}

// SetHTMLBody sets the "html_body" field.
func (u *EmailTemplateUpsertBulk) SetHTMLBody(v string) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetHTMLBody(v)
	})
}

// UpdateHTMLBody sets the "html_body" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateHTMLBody() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateHTMLBody()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *EmailTemplateUpsertBulk) SetIsDefault(v bool) *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *EmailTemplateUpsertBulk) UpdateIsDefault() *EmailTemplateUpsertBulk {
	return u.Update(func(s *EmailTemplateUpsert) {
		s.UpdateIsDefault()
	})
}

// Exec executes the query.
func (u *EmailTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EmailTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EmailTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EmailTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
