// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharedlink"
)

// SharedLinkDelete is the builder for deleting a SharedLink entity.
type SharedLinkDelete struct {
	config
	hooks    []Hook
	mutation *SharedLinkMutation
}

// Where appends a list predicates to the SharedLinkDelete builder.
func (_d *SharedLinkDelete) Where(ps ...predicate.SharedLink) *SharedLinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SharedLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SharedLinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SharedLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sharedlink.Table, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SharedLinkDeleteOne is the builder for deleting a single SharedLink entity.
type SharedLinkDeleteOne struct {
	_d *SharedLinkDelete
}

// Where appends a list predicates to the SharedLinkDelete builder.
func (_d *SharedLinkDeleteOne) Where(ps ...predicate.SharedLink) *SharedLinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SharedLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sharedlink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SharedLinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
