// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharedlink"
)

// SharedLinkCreate is the builder for creating a SharedLink entity.
type SharedLinkCreate struct {
	config
	mutation *SharedLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *SharedLinkCreate) SetCreateBy(v uint32) *SharedLinkCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableCreateBy(v *uint32) *SharedLinkCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SharedLinkCreate) SetCreateTime(v time.Time) *SharedLinkCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableCreateTime(v *time.Time) *SharedLinkCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SharedLinkCreate) SetUpdateTime(v time.Time) *SharedLinkCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableUpdateTime(v *time.Time) *SharedLinkCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SharedLinkCreate) SetDeleteTime(v time.Time) *SharedLinkCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableDeleteTime(v *time.Time) *SharedLinkCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SharedLinkCreate) SetTenantID(v uint32) *SharedLinkCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableTenantID(v *uint32) *SharedLinkCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *SharedLinkCreate) SetResourceType(v sharedlink.ResourceType) *SharedLinkCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *SharedLinkCreate) SetResourceID(v string) *SharedLinkCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetResourceName sets the "resource_name" field.
func (_c *SharedLinkCreate) SetResourceName(v string) *SharedLinkCreate {
	_c.mutation.SetResourceName(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *SharedLinkCreate) SetToken(v string) *SharedLinkCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetEncryptedContent sets the "encrypted_content" field.
func (_c *SharedLinkCreate) SetEncryptedContent(v []byte) *SharedLinkCreate {
	_c.mutation.SetEncryptedContent(v)
	return _c
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (_c *SharedLinkCreate) SetEncryptionNonce(v []byte) *SharedLinkCreate {
	_c.mutation.SetEncryptionNonce(v)
	return _c
}

// SetRecipientEmail sets the "recipient_email" field.
func (_c *SharedLinkCreate) SetRecipientEmail(v string) *SharedLinkCreate {
	_c.mutation.SetRecipientEmail(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *SharedLinkCreate) SetMessage(v string) *SharedLinkCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableMessage(v *string) *SharedLinkCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *SharedLinkCreate) SetTemplateID(v string) *SharedLinkCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableTemplateID(v *string) *SharedLinkCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// SetViewed sets the "viewed" field.
func (_c *SharedLinkCreate) SetViewed(v bool) *SharedLinkCreate {
	_c.mutation.SetViewed(v)
	return _c
}

// SetNillableViewed sets the "viewed" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableViewed(v *bool) *SharedLinkCreate {
	if v != nil {
		_c.SetViewed(*v)
	}
	return _c
}

// SetViewedAt sets the "viewed_at" field.
func (_c *SharedLinkCreate) SetViewedAt(v time.Time) *SharedLinkCreate {
	_c.mutation.SetViewedAt(v)
	return _c
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableViewedAt(v *time.Time) *SharedLinkCreate {
	if v != nil {
		_c.SetViewedAt(*v)
	}
	return _c
}

// SetViewedIP sets the "viewed_ip" field.
func (_c *SharedLinkCreate) SetViewedIP(v string) *SharedLinkCreate {
	_c.mutation.SetViewedIP(v)
	return _c
}

// SetNillableViewedIP sets the "viewed_ip" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableViewedIP(v *string) *SharedLinkCreate {
	if v != nil {
		_c.SetViewedIP(*v)
	}
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *SharedLinkCreate) SetRevoked(v bool) *SharedLinkCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *SharedLinkCreate) SetNillableRevoked(v *bool) *SharedLinkCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SharedLinkCreate) SetID(v string) *SharedLinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SharedLinkMutation object of the builder.
func (_c *SharedLinkCreate) Mutation() *SharedLinkMutation {
	return _c.mutation
}

// Save creates the SharedLink in the database.
func (_c *SharedLinkCreate) Save(ctx context.Context) (*SharedLink, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SharedLinkCreate) SaveX(ctx context.Context) *SharedLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SharedLinkCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := sharedlink.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Viewed(); !ok {
		v := sharedlink.DefaultViewed
		_c.mutation.SetViewed(v)
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		v := sharedlink.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SharedLinkCreate) check() error {
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "SharedLink.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := sharedlink.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "SharedLink.resource_id"`)}
	}
	if v, ok := _c.mutation.ResourceID(); ok {
		if err := sharedlink.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResourceName(); !ok {
		return &ValidationError{Name: "resource_name", err: errors.New(`ent: missing required field "SharedLink.resource_name"`)}
	}
	if v, ok := _c.mutation.ResourceName(); ok {
		if err := sharedlink.ResourceNameValidator(v); err != nil {
			return &ValidationError{Name: "resource_name", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "SharedLink.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := sharedlink.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "SharedLink.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecipientEmail(); !ok {
		return &ValidationError{Name: "recipient_email", err: errors.New(`ent: missing required field "SharedLink.recipient_email"`)}
	}
	if v, ok := _c.mutation.RecipientEmail(); ok {
		if err := sharedlink.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "SharedLink.recipient_email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := sharedlink.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "SharedLink.message": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TemplateID(); ok {
		if err := sharedlink.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "SharedLink.template_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Viewed(); !ok {
		return &ValidationError{Name: "viewed", err: errors.New(`ent: missing required field "SharedLink.viewed"`)}
	}
	if v, ok := _c.mutation.ViewedIP(); ok {
		if err := sharedlink.ViewedIPValidator(v); err != nil {
			return &ValidationError{Name: "viewed_ip", err: fmt.Errorf(`ent: validator failed for field "SharedLink.viewed_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`ent: missing required field "SharedLink.revoked"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sharedlink.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SharedLink.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SharedLinkCreate) sqlSave(ctx context.Context) (*SharedLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SharedLink.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SharedLinkCreate) createSpec() (*SharedLink, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharedlink.Table, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(sharedlink.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(sharedlink.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(sharedlink.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(sharedlink.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(sharedlink.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(sharedlink.FieldResourceType, field.TypeEnum, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(sharedlink.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.ResourceName(); ok {
		_spec.SetField(sharedlink.FieldResourceName, field.TypeString, value)
		_node.ResourceName = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(sharedlink.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.EncryptedContent(); ok {
		_spec.SetField(sharedlink.FieldEncryptedContent, field.TypeBytes, value)
		_node.EncryptedContent = &value
	}
	if value, ok := _c.mutation.EncryptionNonce(); ok {
		_spec.SetField(sharedlink.FieldEncryptionNonce, field.TypeBytes, value)
		_node.EncryptionNonce = &value
	}
	if value, ok := _c.mutation.RecipientEmail(); ok {
		_spec.SetField(sharedlink.FieldRecipientEmail, field.TypeString, value)
		_node.RecipientEmail = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(sharedlink.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(sharedlink.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = &value
	}
	if value, ok := _c.mutation.Viewed(); ok {
		_spec.SetField(sharedlink.FieldViewed, field.TypeBool, value)
		_node.Viewed = value
	}
	if value, ok := _c.mutation.ViewedAt(); ok {
		_spec.SetField(sharedlink.FieldViewedAt, field.TypeTime, value)
		_node.ViewedAt = &value
	}
	if value, ok := _c.mutation.ViewedIP(); ok {
		_spec.SetField(sharedlink.FieldViewedIP, field.TypeString, value)
		_node.ViewedIP = value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(sharedlink.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedLink.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedLinkUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedLinkCreate) OnConflict(opts ...sql.ConflictOption) *SharedLinkUpsertOne {
	_c.conflict = opts
	return &SharedLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedLinkCreate) OnConflictColumns(columns ...string) *SharedLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedLinkUpsertOne{
		create: _c,
	}
}

type (
	// SharedLinkUpsertOne is the builder for "upsert"-ing
	//  one SharedLink node.
	SharedLinkUpsertOne struct {
		create *SharedLinkCreate
	}

	// SharedLinkUpsert is the "OnConflict" setter.
	SharedLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *SharedLinkUpsert) SetCreateBy(v uint32) *SharedLinkUpsert {
	u.Set(sharedlink.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateCreateBy() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *SharedLinkUpsert) AddCreateBy(v uint32) *SharedLinkUpsert {
	u.Add(sharedlink.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SharedLinkUpsert) ClearCreateBy() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SharedLinkUpsert) SetUpdateTime(v time.Time) *SharedLinkUpsert {
	u.Set(sharedlink.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateUpdateTime() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SharedLinkUpsert) ClearUpdateTime() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SharedLinkUpsert) SetDeleteTime(v time.Time) *SharedLinkUpsert {
	u.Set(sharedlink.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateDeleteTime() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SharedLinkUpsert) ClearDeleteTime() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldDeleteTime)
	return u
}

// SetResourceType sets the "resource_type" field.
func (u *SharedLinkUpsert) SetResourceType(v sharedlink.ResourceType) *SharedLinkUpsert {
	u.Set(sharedlink.FieldResourceType, v)
	return u
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateResourceType() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldResourceType)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *SharedLinkUpsert) SetResourceID(v string) *SharedLinkUpsert {
	u.Set(sharedlink.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateResourceID() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldResourceID)
	return u
}

// SetResourceName sets the "resource_name" field.
func (u *SharedLinkUpsert) SetResourceName(v string) *SharedLinkUpsert {
	u.Set(sharedlink.FieldResourceName, v)
	return u
}

// UpdateResourceName sets the "resource_name" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateResourceName() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldResourceName)
	return u
}

// SetToken sets the "token" field.
func (u *SharedLinkUpsert) SetToken(v string) *SharedLinkUpsert {
	u.Set(sharedlink.FieldToken, v)
	return u
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateToken() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldToken)
	return u
}

// SetEncryptedContent sets the "encrypted_content" field.
func (u *SharedLinkUpsert) SetEncryptedContent(v []byte) *SharedLinkUpsert {
	u.Set(sharedlink.FieldEncryptedContent, v)
	return u
}

// UpdateEncryptedContent sets the "encrypted_content" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateEncryptedContent() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldEncryptedContent)
	return u
}

// ClearEncryptedContent clears the value of the "encrypted_content" field.
func (u *SharedLinkUpsert) ClearEncryptedContent() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldEncryptedContent)
	return u
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (u *SharedLinkUpsert) SetEncryptionNonce(v []byte) *SharedLinkUpsert {
	u.Set(sharedlink.FieldEncryptionNonce, v)
	return u
}

// UpdateEncryptionNonce sets the "encryption_nonce" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateEncryptionNonce() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldEncryptionNonce)
	return u
}

// ClearEncryptionNonce clears the value of the "encryption_nonce" field.
func (u *SharedLinkUpsert) ClearEncryptionNonce() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldEncryptionNonce)
	return u
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *SharedLinkUpsert) SetRecipientEmail(v string) *SharedLinkUpsert {
	u.Set(sharedlink.FieldRecipientEmail, v)
	return u
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateRecipientEmail() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldRecipientEmail)
	return u
}

// SetMessage sets the "message" field.
func (u *SharedLinkUpsert) SetMessage(v string) *SharedLinkUpsert {
	u.Set(sharedlink.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateMessage() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *SharedLinkUpsert) ClearMessage() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldMessage)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *SharedLinkUpsert) SetTemplateID(v string) *SharedLinkUpsert {
	u.Set(sharedlink.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateTemplateID() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldTemplateID)
	return u
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *SharedLinkUpsert) ClearTemplateID() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldTemplateID)
	return u
}

// SetViewed sets the "viewed" field.
func (u *SharedLinkUpsert) SetViewed(v bool) *SharedLinkUpsert {
	u.Set(sharedlink.FieldViewed, v)
	return u
}

// UpdateViewed sets the "viewed" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateViewed() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldViewed)
	return u
}

// SetViewedAt sets the "viewed_at" field.
func (u *SharedLinkUpsert) SetViewedAt(v time.Time) *SharedLinkUpsert {
	u.Set(sharedlink.FieldViewedAt, v)
	return u
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateViewedAt() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldViewedAt)
	return u
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (u *SharedLinkUpsert) ClearViewedAt() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldViewedAt)
	return u
}

// SetViewedIP sets the "viewed_ip" field.
func (u *SharedLinkUpsert) SetViewedIP(v string) *SharedLinkUpsert {
	u.Set(sharedlink.FieldViewedIP, v)
	return u
}

// UpdateViewedIP sets the "viewed_ip" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateViewedIP() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldViewedIP)
	return u
}

// ClearViewedIP clears the value of the "viewed_ip" field.
func (u *SharedLinkUpsert) ClearViewedIP() *SharedLinkUpsert {
	u.SetNull(sharedlink.FieldViewedIP)
	return u
}

// SetRevoked sets the "revoked" field.
func (u *SharedLinkUpsert) SetRevoked(v bool) *SharedLinkUpsert {
	u.Set(sharedlink.FieldRevoked, v)
	return u
}

// UpdateRevoked sets the "revoked" field to the value that was provided on create.
func (u *SharedLinkUpsert) UpdateRevoked() *SharedLinkUpsert {
	u.SetExcluded(sharedlink.FieldRevoked)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SharedLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sharedlink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SharedLinkUpsertOne) UpdateNewValues() *SharedLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(sharedlink.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(sharedlink.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(sharedlink.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharedLinkUpsertOne) Ignore() *SharedLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedLinkUpsertOne) DoNothing() *SharedLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedLinkCreate.OnConflict
// documentation for more info.
func (u *SharedLinkUpsertOne) Update(set func(*SharedLinkUpsert)) *SharedLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SharedLinkUpsertOne) SetCreateBy(v uint32) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SharedLinkUpsertOne) AddCreateBy(v uint32) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateCreateBy() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SharedLinkUpsertOne) ClearCreateBy() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SharedLinkUpsertOne) SetUpdateTime(v time.Time) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateUpdateTime() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SharedLinkUpsertOne) ClearUpdateTime() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SharedLinkUpsertOne) SetDeleteTime(v time.Time) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateDeleteTime() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SharedLinkUpsertOne) ClearDeleteTime() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearDeleteTime()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *SharedLinkUpsertOne) SetResourceType(v sharedlink.ResourceType) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateResourceType() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *SharedLinkUpsertOne) SetResourceID(v string) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateResourceID() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateResourceID()
	})
}

// SetResourceName sets the "resource_name" field.
func (u *SharedLinkUpsertOne) SetResourceName(v string) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetResourceName(v)
	})
}

// UpdateResourceName sets the "resource_name" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateResourceName() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateResourceName()
	})
}

// SetToken sets the "token" field.
func (u *SharedLinkUpsertOne) SetToken(v string) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateToken() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateToken()
	})
}

// SetEncryptedContent sets the "encrypted_content" field.
func (u *SharedLinkUpsertOne) SetEncryptedContent(v []byte) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetEncryptedContent(v)
	})
}

// UpdateEncryptedContent sets the "encrypted_content" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateEncryptedContent() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateEncryptedContent()
	})
}

// ClearEncryptedContent clears the value of the "encrypted_content" field.
func (u *SharedLinkUpsertOne) ClearEncryptedContent() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearEncryptedContent()
	})
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (u *SharedLinkUpsertOne) SetEncryptionNonce(v []byte) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetEncryptionNonce(v)
	})
}

// UpdateEncryptionNonce sets the "encryption_nonce" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateEncryptionNonce() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateEncryptionNonce()
	})
}

// ClearEncryptionNonce clears the value of the "encryption_nonce" field.
func (u *SharedLinkUpsertOne) ClearEncryptionNonce() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearEncryptionNonce()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *SharedLinkUpsertOne) SetRecipientEmail(v string) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateRecipientEmail() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetMessage sets the "message" field.
func (u *SharedLinkUpsertOne) SetMessage(v string) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateMessage() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *SharedLinkUpsertOne) ClearMessage() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearMessage()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *SharedLinkUpsertOne) SetTemplateID(v string) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateTemplateID() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *SharedLinkUpsertOne) ClearTemplateID() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearTemplateID()
	})
}

// SetViewed sets the "viewed" field.
func (u *SharedLinkUpsertOne) SetViewed(v bool) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetViewed(v)
	})
}

// UpdateViewed sets the "viewed" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateViewed() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateViewed()
	})
}

// SetViewedAt sets the "viewed_at" field.
func (u *SharedLinkUpsertOne) SetViewedAt(v time.Time) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetViewedAt(v)
	})
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateViewedAt() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateViewedAt()
	})
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (u *SharedLinkUpsertOne) ClearViewedAt() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearViewedAt()
	})
}

// SetViewedIP sets the "viewed_ip" field.
func (u *SharedLinkUpsertOne) SetViewedIP(v string) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetViewedIP(v)
	})
}

// UpdateViewedIP sets the "viewed_ip" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateViewedIP() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateViewedIP()
	})
}

// ClearViewedIP clears the value of the "viewed_ip" field.
func (u *SharedLinkUpsertOne) ClearViewedIP() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearViewedIP()
	})
}

// SetRevoked sets the "revoked" field.
func (u *SharedLinkUpsertOne) SetRevoked(v bool) *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetRevoked(v)
	})
}

// UpdateRevoked sets the "revoked" field to the value that was provided on create.
func (u *SharedLinkUpsertOne) UpdateRevoked() *SharedLinkUpsertOne {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateRevoked()
	})
}

// Exec executes the query.
func (u *SharedLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharedLinkUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SharedLinkUpsertOne.ID is not supported by MySQL driver. Use SharedLinkUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharedLinkUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SharedLinkCreateBulk is the builder for creating many SharedLink entities in bulk.
type SharedLinkCreateBulk struct {
	config
	err      error
	builders []*SharedLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the SharedLink entities in the database.
func (_c *SharedLinkCreateBulk) Save(ctx context.Context) ([]*SharedLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SharedLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SharedLinkCreateBulk) SaveX(ctx context.Context) []*SharedLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharedLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharedLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharedLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharedLinkUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SharedLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharedLinkUpsertBulk {
	_c.conflict = opts
	return &SharedLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharedLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharedLinkCreateBulk) OnConflictColumns(columns ...string) *SharedLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharedLinkUpsertBulk{
		create: _c,
	}
}

// SharedLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of SharedLink nodes.
type SharedLinkUpsertBulk struct {
	create *SharedLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharedLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sharedlink.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SharedLinkUpsertBulk) UpdateNewValues() *SharedLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(sharedlink.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(sharedlink.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(sharedlink.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharedLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharedLinkUpsertBulk) Ignore() *SharedLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharedLinkUpsertBulk) DoNothing() *SharedLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharedLinkCreateBulk.OnConflict
// documentation for more info.
func (u *SharedLinkUpsertBulk) Update(set func(*SharedLinkUpsert)) *SharedLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharedLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SharedLinkUpsertBulk) SetCreateBy(v uint32) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SharedLinkUpsertBulk) AddCreateBy(v uint32) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateCreateBy() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SharedLinkUpsertBulk) ClearCreateBy() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SharedLinkUpsertBulk) SetUpdateTime(v time.Time) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateUpdateTime() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SharedLinkUpsertBulk) ClearUpdateTime() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SharedLinkUpsertBulk) SetDeleteTime(v time.Time) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateDeleteTime() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SharedLinkUpsertBulk) ClearDeleteTime() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearDeleteTime()
	})
}

// SetResourceType sets the "resource_type" field.
func (u *SharedLinkUpsertBulk) SetResourceType(v sharedlink.ResourceType) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetResourceType(v)
	})
}

// UpdateResourceType sets the "resource_type" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateResourceType() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateResourceType()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *SharedLinkUpsertBulk) SetResourceID(v string) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateResourceID() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateResourceID()
	})
}

// SetResourceName sets the "resource_name" field.
func (u *SharedLinkUpsertBulk) SetResourceName(v string) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetResourceName(v)
	})
}

// UpdateResourceName sets the "resource_name" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateResourceName() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateResourceName()
	})
}

// SetToken sets the "token" field.
func (u *SharedLinkUpsertBulk) SetToken(v string) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetToken(v)
	})
}

// UpdateToken sets the "token" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateToken() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateToken()
	})
}

// SetEncryptedContent sets the "encrypted_content" field.
func (u *SharedLinkUpsertBulk) SetEncryptedContent(v []byte) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetEncryptedContent(v)
	})
}

// UpdateEncryptedContent sets the "encrypted_content" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateEncryptedContent() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateEncryptedContent()
	})
}

// ClearEncryptedContent clears the value of the "encrypted_content" field.
func (u *SharedLinkUpsertBulk) ClearEncryptedContent() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearEncryptedContent()
	})
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (u *SharedLinkUpsertBulk) SetEncryptionNonce(v []byte) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetEncryptionNonce(v)
	})
}

// UpdateEncryptionNonce sets the "encryption_nonce" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateEncryptionNonce() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateEncryptionNonce()
	})
}

// ClearEncryptionNonce clears the value of the "encryption_nonce" field.
func (u *SharedLinkUpsertBulk) ClearEncryptionNonce() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearEncryptionNonce()
	})
}

// SetRecipientEmail sets the "recipient_email" field.
func (u *SharedLinkUpsertBulk) SetRecipientEmail(v string) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetRecipientEmail(v)
	})
}

// UpdateRecipientEmail sets the "recipient_email" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateRecipientEmail() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateRecipientEmail()
	})
}

// SetMessage sets the "message" field.
func (u *SharedLinkUpsertBulk) SetMessage(v string) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateMessage() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *SharedLinkUpsertBulk) ClearMessage() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearMessage()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *SharedLinkUpsertBulk) SetTemplateID(v string) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateTemplateID() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateTemplateID()
	})
}

// ClearTemplateID clears the value of the "template_id" field.
func (u *SharedLinkUpsertBulk) ClearTemplateID() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearTemplateID()
	})
}

// SetViewed sets the "viewed" field.
func (u *SharedLinkUpsertBulk) SetViewed(v bool) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetViewed(v)
	})
}

// UpdateViewed sets the "viewed" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateViewed() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateViewed()
	})
}

// SetViewedAt sets the "viewed_at" field.
func (u *SharedLinkUpsertBulk) SetViewedAt(v time.Time) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetViewedAt(v)
	})
}

// UpdateViewedAt sets the "viewed_at" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateViewedAt() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateViewedAt()
	})
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (u *SharedLinkUpsertBulk) ClearViewedAt() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearViewedAt()
	})
}

// SetViewedIP sets the "viewed_ip" field.
func (u *SharedLinkUpsertBulk) SetViewedIP(v string) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetViewedIP(v)
	})
}

// UpdateViewedIP sets the "viewed_ip" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateViewedIP() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateViewedIP()
	})
}

// ClearViewedIP clears the value of the "viewed_ip" field.
func (u *SharedLinkUpsertBulk) ClearViewedIP() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.ClearViewedIP()
	})
}

// SetRevoked sets the "revoked" field.
func (u *SharedLinkUpsertBulk) SetRevoked(v bool) *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.SetRevoked(v)
	})
}

// UpdateRevoked sets the "revoked" field to the value that was provided on create.
func (u *SharedLinkUpsertBulk) UpdateRevoked() *SharedLinkUpsertBulk {
	return u.Update(func(s *SharedLinkUpsert) {
		s.UpdateRevoked()
	})
}

// Exec executes the query.
func (u *SharedLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharedLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharedLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharedLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
