// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharedlink"
)

// SharedLink is the model entity for the SharedLink schema.
type SharedLink struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Type of resource being shared
	ResourceType sharedlink.ResourceType `json:"resource_type,omitempty"`
	// ID of the shared resource
	ResourceID string `json:"resource_id,omitempty"`
	// Display name of the shared resource
	ResourceName string `json:"resource_name,omitempty"`
	// Unique share token (64 hex chars)
	Token string `json:"token,omitempty"`
	// AES-256-GCM encrypted content
	EncryptedContent []byte `json:"encrypted_content,omitempty"`
	// AES-256-GCM nonce
	EncryptionNonce []byte `json:"encryption_nonce,omitempty"`
	// Recipient email address
	RecipientEmail string `json:"recipient_email,omitempty"`
	// Optional message to recipient
	Message string `json:"message,omitempty"`
	// Email template ID used
	TemplateID *string `json:"template_id,omitempty"`
	// Whether the share has been viewed
	Viewed bool `json:"viewed,omitempty"`
	// When the share was viewed
	ViewedAt *time.Time `json:"viewed_at,omitempty"`
	// IP address of viewer
	ViewedIP string `json:"viewed_ip,omitempty"`
	// Whether the share has been revoked
	Revoked      bool `json:"revoked,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SharedLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharedlink.FieldEncryptedContent, sharedlink.FieldEncryptionNonce:
			values[i] = new([]byte)
		case sharedlink.FieldViewed, sharedlink.FieldRevoked:
			values[i] = new(sql.NullBool)
		case sharedlink.FieldCreateBy, sharedlink.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case sharedlink.FieldID, sharedlink.FieldResourceType, sharedlink.FieldResourceID, sharedlink.FieldResourceName, sharedlink.FieldToken, sharedlink.FieldRecipientEmail, sharedlink.FieldMessage, sharedlink.FieldTemplateID, sharedlink.FieldViewedIP:
			values[i] = new(sql.NullString)
		case sharedlink.FieldCreateTime, sharedlink.FieldUpdateTime, sharedlink.FieldDeleteTime, sharedlink.FieldViewedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SharedLink fields.
func (_m *SharedLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharedlink.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sharedlink.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case sharedlink.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case sharedlink.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case sharedlink.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case sharedlink.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case sharedlink.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				_m.ResourceType = sharedlink.ResourceType(value.String)
			}
		case sharedlink.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.String
			}
		case sharedlink.FieldResourceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_name", values[i])
			} else if value.Valid {
				_m.ResourceName = value.String
			}
		case sharedlink.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case sharedlink.FieldEncryptedContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_content", values[i])
			} else if value != nil {
				_m.EncryptedContent = *value
			}
		case sharedlink.FieldEncryptionNonce:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encryption_nonce", values[i])
			} else if value != nil {
				_m.EncryptionNonce = *value
			}
		case sharedlink.FieldRecipientEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field recipient_email", values[i])
			} else if value.Valid {
				_m.RecipientEmail = value.String
			}
		case sharedlink.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case sharedlink.FieldTemplateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = new(string)
				*_m.TemplateID = value.String
			}
		case sharedlink.FieldViewed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field viewed", values[i])
			} else if value.Valid {
				_m.Viewed = value.Bool
			}
		case sharedlink.FieldViewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field viewed_at", values[i])
			} else if value.Valid {
				_m.ViewedAt = new(time.Time)
				*_m.ViewedAt = value.Time
			}
		case sharedlink.FieldViewedIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field viewed_ip", values[i])
			} else if value.Valid {
				_m.ViewedIP = value.String
			}
		case sharedlink.FieldRevoked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field revoked", values[i])
			} else if value.Valid {
				_m.Revoked = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SharedLink.
// This includes values selected through modifiers, order, etc.
func (_m *SharedLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SharedLink.
// Note that you need to call SharedLink.Unwrap() before calling this method if this SharedLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SharedLink) Update() *SharedLinkUpdateOne {
	return NewSharedLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SharedLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SharedLink) Unwrap() *SharedLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SharedLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SharedLink) String() string {
	var builder strings.Builder
	builder.WriteString("SharedLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResourceType))
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(_m.ResourceID)
	builder.WriteString(", ")
	builder.WriteString("resource_name=")
	builder.WriteString(_m.ResourceName)
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("encrypted_content=")
	builder.WriteString(fmt.Sprintf("%v", _m.EncryptedContent))
	builder.WriteString(", ")
	builder.WriteString("encryption_nonce=")
	builder.WriteString(fmt.Sprintf("%v", _m.EncryptionNonce))
	builder.WriteString(", ")
	builder.WriteString("recipient_email=")
	builder.WriteString(_m.RecipientEmail)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	if v := _m.TemplateID; v != nil {
		builder.WriteString("template_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("viewed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Viewed))
	builder.WriteString(", ")
	if v := _m.ViewedAt; v != nil {
		builder.WriteString("viewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("viewed_ip=")
	builder.WriteString(_m.ViewedIP)
	builder.WriteString(", ")
	builder.WriteString("revoked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revoked))
	builder.WriteByte(')')
	return builder.String()
}

// SharedLinks is a parsable slice of SharedLink.
type SharedLinks []*SharedLink
