// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharedlink"
)

// SharedLinkUpdate is the builder for updating SharedLink entities.
type SharedLinkUpdate struct {
	config
	hooks     []Hook
	mutation  *SharedLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SharedLinkUpdate builder.
func (_u *SharedLinkUpdate) Where(ps ...predicate.SharedLink) *SharedLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *SharedLinkUpdate) SetCreateBy(v uint32) *SharedLinkUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableCreateBy(v *uint32) *SharedLinkUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SharedLinkUpdate) AddCreateBy(v int32) *SharedLinkUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SharedLinkUpdate) ClearCreateBy() *SharedLinkUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SharedLinkUpdate) SetUpdateTime(v time.Time) *SharedLinkUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableUpdateTime(v *time.Time) *SharedLinkUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SharedLinkUpdate) ClearUpdateTime() *SharedLinkUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SharedLinkUpdate) SetDeleteTime(v time.Time) *SharedLinkUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableDeleteTime(v *time.Time) *SharedLinkUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SharedLinkUpdate) ClearDeleteTime() *SharedLinkUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *SharedLinkUpdate) SetResourceType(v sharedlink.ResourceType) *SharedLinkUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableResourceType(v *sharedlink.ResourceType) *SharedLinkUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *SharedLinkUpdate) SetResourceID(v string) *SharedLinkUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableResourceID(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *SharedLinkUpdate) SetResourceName(v string) *SharedLinkUpdate {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableResourceName(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *SharedLinkUpdate) SetToken(v string) *SharedLinkUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableToken(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetEncryptedContent sets the "encrypted_content" field.
func (_u *SharedLinkUpdate) SetEncryptedContent(v []byte) *SharedLinkUpdate {
	_u.mutation.SetEncryptedContent(v)
	return _u
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (_u *SharedLinkUpdate) SetEncryptionNonce(v []byte) *SharedLinkUpdate {
	_u.mutation.SetEncryptionNonce(v)
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *SharedLinkUpdate) SetRecipientEmail(v string) *SharedLinkUpdate {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableRecipientEmail(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *SharedLinkUpdate) SetMessage(v string) *SharedLinkUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableMessage(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *SharedLinkUpdate) ClearMessage() *SharedLinkUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *SharedLinkUpdate) SetTemplateID(v string) *SharedLinkUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableTemplateID(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// ClearTemplateID clears the value of the "template_id" field.
func (_u *SharedLinkUpdate) ClearTemplateID() *SharedLinkUpdate {
	_u.mutation.ClearTemplateID()
	return _u
}

// SetViewed sets the "viewed" field.
func (_u *SharedLinkUpdate) SetViewed(v bool) *SharedLinkUpdate {
	_u.mutation.SetViewed(v)
	return _u
}

// SetNillableViewed sets the "viewed" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableViewed(v *bool) *SharedLinkUpdate {
	if v != nil {
		_u.SetViewed(*v)
	}
	return _u
}

// SetViewedAt sets the "viewed_at" field.
func (_u *SharedLinkUpdate) SetViewedAt(v time.Time) *SharedLinkUpdate {
	_u.mutation.SetViewedAt(v)
	return _u
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableViewedAt(v *time.Time) *SharedLinkUpdate {
	if v != nil {
		_u.SetViewedAt(*v)
	}
	return _u
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (_u *SharedLinkUpdate) ClearViewedAt() *SharedLinkUpdate {
	_u.mutation.ClearViewedAt()
	return _u
}

// SetViewedIP sets the "viewed_ip" field.
func (_u *SharedLinkUpdate) SetViewedIP(v string) *SharedLinkUpdate {
	_u.mutation.SetViewedIP(v)
	return _u
}

// SetNillableViewedIP sets the "viewed_ip" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableViewedIP(v *string) *SharedLinkUpdate {
	if v != nil {
		_u.SetViewedIP(*v)
	}
	return _u
}

// ClearViewedIP clears the value of the "viewed_ip" field.
func (_u *SharedLinkUpdate) ClearViewedIP() *SharedLinkUpdate {
	_u.mutation.ClearViewedIP()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *SharedLinkUpdate) SetRevoked(v bool) *SharedLinkUpdate {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *SharedLinkUpdate) SetNillableRevoked(v *bool) *SharedLinkUpdate {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// Mutation returns the SharedLinkMutation object of the builder.
func (_u *SharedLinkUpdate) Mutation() *SharedLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SharedLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SharedLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedLinkUpdate) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := sharedlink.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := sharedlink.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceName(); ok {
		if err := sharedlink.ResourceNameValidator(v); err != nil {
			return &ValidationError{Name: "resource_name", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := sharedlink.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "SharedLink.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := sharedlink.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "SharedLink.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := sharedlink.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "SharedLink.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := sharedlink.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "SharedLink.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewedIP(); ok {
		if err := sharedlink.ViewedIPValidator(v); err != nil {
			return &ValidationError{Name: "viewed_ip", err: fmt.Errorf(`ent: validator failed for field "SharedLink.viewed_ip": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SharedLinkUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SharedLinkUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SharedLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedlink.Table, sharedlink.Columns, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(sharedlink.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(sharedlink.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(sharedlink.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(sharedlink.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(sharedlink.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(sharedlink.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(sharedlink.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(sharedlink.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(sharedlink.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(sharedlink.FieldResourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(sharedlink.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(sharedlink.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(sharedlink.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedContent(); ok {
		_spec.SetField(sharedlink.FieldEncryptedContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.EncryptionNonce(); ok {
		_spec.SetField(sharedlink.FieldEncryptionNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(sharedlink.FieldRecipientEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(sharedlink.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(sharedlink.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(sharedlink.FieldTemplateID, field.TypeString, value)
	}
	if _u.mutation.TemplateIDCleared() {
		_spec.ClearField(sharedlink.FieldTemplateID, field.TypeString)
	}
	if value, ok := _u.mutation.Viewed(); ok {
		_spec.SetField(sharedlink.FieldViewed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewedAt(); ok {
		_spec.SetField(sharedlink.FieldViewedAt, field.TypeTime, value)
	}
	if _u.mutation.ViewedAtCleared() {
		_spec.ClearField(sharedlink.FieldViewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewedIP(); ok {
		_spec.SetField(sharedlink.FieldViewedIP, field.TypeString, value)
	}
	if _u.mutation.ViewedIPCleared() {
		_spec.ClearField(sharedlink.FieldViewedIP, field.TypeString)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(sharedlink.FieldRevoked, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SharedLinkUpdateOne is the builder for updating a single SharedLink entity.
type SharedLinkUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SharedLinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *SharedLinkUpdateOne) SetCreateBy(v uint32) *SharedLinkUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableCreateBy(v *uint32) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SharedLinkUpdateOne) AddCreateBy(v int32) *SharedLinkUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SharedLinkUpdateOne) ClearCreateBy() *SharedLinkUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SharedLinkUpdateOne) SetUpdateTime(v time.Time) *SharedLinkUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableUpdateTime(v *time.Time) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SharedLinkUpdateOne) ClearUpdateTime() *SharedLinkUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SharedLinkUpdateOne) SetDeleteTime(v time.Time) *SharedLinkUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableDeleteTime(v *time.Time) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SharedLinkUpdateOne) ClearDeleteTime() *SharedLinkUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *SharedLinkUpdateOne) SetResourceType(v sharedlink.ResourceType) *SharedLinkUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableResourceType(v *sharedlink.ResourceType) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *SharedLinkUpdateOne) SetResourceID(v string) *SharedLinkUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableResourceID(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResourceName sets the "resource_name" field.
func (_u *SharedLinkUpdateOne) SetResourceName(v string) *SharedLinkUpdateOne {
	_u.mutation.SetResourceName(v)
	return _u
}

// SetNillableResourceName sets the "resource_name" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableResourceName(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetResourceName(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *SharedLinkUpdateOne) SetToken(v string) *SharedLinkUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableToken(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetEncryptedContent sets the "encrypted_content" field.
func (_u *SharedLinkUpdateOne) SetEncryptedContent(v []byte) *SharedLinkUpdateOne {
	_u.mutation.SetEncryptedContent(v)
	return _u
}

// SetEncryptionNonce sets the "encryption_nonce" field.
func (_u *SharedLinkUpdateOne) SetEncryptionNonce(v []byte) *SharedLinkUpdateOne {
	_u.mutation.SetEncryptionNonce(v)
	return _u
}

// SetRecipientEmail sets the "recipient_email" field.
func (_u *SharedLinkUpdateOne) SetRecipientEmail(v string) *SharedLinkUpdateOne {
	_u.mutation.SetRecipientEmail(v)
	return _u
}

// SetNillableRecipientEmail sets the "recipient_email" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableRecipientEmail(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetRecipientEmail(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *SharedLinkUpdateOne) SetMessage(v string) *SharedLinkUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableMessage(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *SharedLinkUpdateOne) ClearMessage() *SharedLinkUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *SharedLinkUpdateOne) SetTemplateID(v string) *SharedLinkUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableTemplateID(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// ClearTemplateID clears the value of the "template_id" field.
func (_u *SharedLinkUpdateOne) ClearTemplateID() *SharedLinkUpdateOne {
	_u.mutation.ClearTemplateID()
	return _u
}

// SetViewed sets the "viewed" field.
func (_u *SharedLinkUpdateOne) SetViewed(v bool) *SharedLinkUpdateOne {
	_u.mutation.SetViewed(v)
	return _u
}

// SetNillableViewed sets the "viewed" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableViewed(v *bool) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetViewed(*v)
	}
	return _u
}

// SetViewedAt sets the "viewed_at" field.
func (_u *SharedLinkUpdateOne) SetViewedAt(v time.Time) *SharedLinkUpdateOne {
	_u.mutation.SetViewedAt(v)
	return _u
}

// SetNillableViewedAt sets the "viewed_at" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableViewedAt(v *time.Time) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetViewedAt(*v)
	}
	return _u
}

// ClearViewedAt clears the value of the "viewed_at" field.
func (_u *SharedLinkUpdateOne) ClearViewedAt() *SharedLinkUpdateOne {
	_u.mutation.ClearViewedAt()
	return _u
}

// SetViewedIP sets the "viewed_ip" field.
func (_u *SharedLinkUpdateOne) SetViewedIP(v string) *SharedLinkUpdateOne {
	_u.mutation.SetViewedIP(v)
	return _u
}

// SetNillableViewedIP sets the "viewed_ip" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableViewedIP(v *string) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetViewedIP(*v)
	}
	return _u
}

// ClearViewedIP clears the value of the "viewed_ip" field.
func (_u *SharedLinkUpdateOne) ClearViewedIP() *SharedLinkUpdateOne {
	_u.mutation.ClearViewedIP()
	return _u
}

// SetRevoked sets the "revoked" field.
func (_u *SharedLinkUpdateOne) SetRevoked(v bool) *SharedLinkUpdateOne {
	_u.mutation.SetRevoked(v)
	return _u
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_u *SharedLinkUpdateOne) SetNillableRevoked(v *bool) *SharedLinkUpdateOne {
	if v != nil {
		_u.SetRevoked(*v)
	}
	return _u
}

// Mutation returns the SharedLinkMutation object of the builder.
func (_u *SharedLinkUpdateOne) Mutation() *SharedLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the SharedLinkUpdate builder.
func (_u *SharedLinkUpdateOne) Where(ps ...predicate.SharedLink) *SharedLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SharedLinkUpdateOne) Select(field string, fields ...string) *SharedLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SharedLink entity.
func (_u *SharedLinkUpdateOne) Save(ctx context.Context) (*SharedLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharedLinkUpdateOne) SaveX(ctx context.Context) *SharedLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SharedLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharedLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharedLinkUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := sharedlink.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceID(); ok {
		if err := sharedlink.ResourceIDValidator(v); err != nil {
			return &ValidationError{Name: "resource_id", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResourceName(); ok {
		if err := sharedlink.ResourceNameValidator(v); err != nil {
			return &ValidationError{Name: "resource_name", err: fmt.Errorf(`ent: validator failed for field "SharedLink.resource_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := sharedlink.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "SharedLink.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecipientEmail(); ok {
		if err := sharedlink.RecipientEmailValidator(v); err != nil {
			return &ValidationError{Name: "recipient_email", err: fmt.Errorf(`ent: validator failed for field "SharedLink.recipient_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := sharedlink.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "SharedLink.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TemplateID(); ok {
		if err := sharedlink.TemplateIDValidator(v); err != nil {
			return &ValidationError{Name: "template_id", err: fmt.Errorf(`ent: validator failed for field "SharedLink.template_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ViewedIP(); ok {
		if err := sharedlink.ViewedIPValidator(v); err != nil {
			return &ValidationError{Name: "viewed_ip", err: fmt.Errorf(`ent: validator failed for field "SharedLink.viewed_ip": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SharedLinkUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SharedLinkUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SharedLinkUpdateOne) sqlSave(ctx context.Context) (_node *SharedLink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharedlink.Table, sharedlink.Columns, sqlgraph.NewFieldSpec(sharedlink.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharedLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedlink.FieldID)
		for _, f := range fields {
			if !sharedlink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharedlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(sharedlink.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(sharedlink.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(sharedlink.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(sharedlink.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(sharedlink.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(sharedlink.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(sharedlink.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(sharedlink.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(sharedlink.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(sharedlink.FieldResourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(sharedlink.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceName(); ok {
		_spec.SetField(sharedlink.FieldResourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(sharedlink.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedContent(); ok {
		_spec.SetField(sharedlink.FieldEncryptedContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.EncryptionNonce(); ok {
		_spec.SetField(sharedlink.FieldEncryptionNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.RecipientEmail(); ok {
		_spec.SetField(sharedlink.FieldRecipientEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(sharedlink.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(sharedlink.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(sharedlink.FieldTemplateID, field.TypeString, value)
	}
	if _u.mutation.TemplateIDCleared() {
		_spec.ClearField(sharedlink.FieldTemplateID, field.TypeString)
	}
	if value, ok := _u.mutation.Viewed(); ok {
		_spec.SetField(sharedlink.FieldViewed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewedAt(); ok {
		_spec.SetField(sharedlink.FieldViewedAt, field.TypeTime, value)
	}
	if _u.mutation.ViewedAtCleared() {
		_spec.ClearField(sharedlink.FieldViewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ViewedIP(); ok {
		_spec.SetField(sharedlink.FieldViewedIP, field.TypeString, value)
	}
	if _u.mutation.ViewedIPCleared() {
		_spec.ClearField(sharedlink.FieldViewedIP, field.TypeString)
	}
	if value, ok := _u.mutation.Revoked(); ok {
		_spec.SetField(sharedlink.FieldRevoked, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SharedLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharedlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
