// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharepolicy"
)

// SharePolicyUpdate is the builder for updating SharePolicy entities.
type SharePolicyUpdate struct {
	config
	hooks     []Hook
	mutation  *SharePolicyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SharePolicyUpdate builder.
func (_u *SharePolicyUpdate) Where(ps ...predicate.SharePolicy) *SharePolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *SharePolicyUpdate) SetCreateBy(v uint32) *SharePolicyUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableCreateBy(v *uint32) *SharePolicyUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SharePolicyUpdate) AddCreateBy(v int32) *SharePolicyUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SharePolicyUpdate) ClearCreateBy() *SharePolicyUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SharePolicyUpdate) SetUpdateTime(v time.Time) *SharePolicyUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableUpdateTime(v *time.Time) *SharePolicyUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SharePolicyUpdate) ClearUpdateTime() *SharePolicyUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SharePolicyUpdate) SetDeleteTime(v time.Time) *SharePolicyUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableDeleteTime(v *time.Time) *SharePolicyUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SharePolicyUpdate) ClearDeleteTime() *SharePolicyUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetShareLinkID sets the "share_link_id" field.
func (_u *SharePolicyUpdate) SetShareLinkID(v string) *SharePolicyUpdate {
	_u.mutation.SetShareLinkID(v)
	return _u
}

// SetNillableShareLinkID sets the "share_link_id" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableShareLinkID(v *string) *SharePolicyUpdate {
	if v != nil {
		_u.SetShareLinkID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SharePolicyUpdate) SetType(v sharepolicy.Type) *SharePolicyUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableType(v *sharepolicy.Type) *SharePolicyUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *SharePolicyUpdate) SetMethod(v sharepolicy.Method) *SharePolicyUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableMethod(v *sharepolicy.Method) *SharePolicyUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SharePolicyUpdate) SetValue(v string) *SharePolicyUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableValue(v *string) *SharePolicyUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *SharePolicyUpdate) SetReason(v string) *SharePolicyUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *SharePolicyUpdate) SetNillableReason(v *string) *SharePolicyUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *SharePolicyUpdate) ClearReason() *SharePolicyUpdate {
	_u.mutation.ClearReason()
	return _u
}

// Mutation returns the SharePolicyMutation object of the builder.
func (_u *SharePolicyUpdate) Mutation() *SharePolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SharePolicyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharePolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SharePolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharePolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharePolicyUpdate) check() error {
	if v, ok := _u.mutation.ShareLinkID(); ok {
		if err := sharepolicy.ShareLinkIDValidator(v); err != nil {
			return &ValidationError{Name: "share_link_id", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.share_link_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := sharepolicy.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := sharepolicy.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := sharepolicy.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := sharepolicy.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.reason": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SharePolicyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SharePolicyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SharePolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharepolicy.Table, sharepolicy.Columns, sqlgraph.NewFieldSpec(sharepolicy.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(sharepolicy.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(sharepolicy.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(sharepolicy.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(sharepolicy.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(sharepolicy.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(sharepolicy.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(sharepolicy.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(sharepolicy.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(sharepolicy.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ShareLinkID(); ok {
		_spec.SetField(sharepolicy.FieldShareLinkID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sharepolicy.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(sharepolicy.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(sharepolicy.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(sharepolicy.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(sharepolicy.FieldReason, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SharePolicyUpdateOne is the builder for updating a single SharePolicy entity.
type SharePolicyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SharePolicyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *SharePolicyUpdateOne) SetCreateBy(v uint32) *SharePolicyUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableCreateBy(v *uint32) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SharePolicyUpdateOne) AddCreateBy(v int32) *SharePolicyUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SharePolicyUpdateOne) ClearCreateBy() *SharePolicyUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SharePolicyUpdateOne) SetUpdateTime(v time.Time) *SharePolicyUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableUpdateTime(v *time.Time) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *SharePolicyUpdateOne) ClearUpdateTime() *SharePolicyUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SharePolicyUpdateOne) SetDeleteTime(v time.Time) *SharePolicyUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableDeleteTime(v *time.Time) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SharePolicyUpdateOne) ClearDeleteTime() *SharePolicyUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetShareLinkID sets the "share_link_id" field.
func (_u *SharePolicyUpdateOne) SetShareLinkID(v string) *SharePolicyUpdateOne {
	_u.mutation.SetShareLinkID(v)
	return _u
}

// SetNillableShareLinkID sets the "share_link_id" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableShareLinkID(v *string) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetShareLinkID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SharePolicyUpdateOne) SetType(v sharepolicy.Type) *SharePolicyUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableType(v *sharepolicy.Type) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *SharePolicyUpdateOne) SetMethod(v sharepolicy.Method) *SharePolicyUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableMethod(v *sharepolicy.Method) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SharePolicyUpdateOne) SetValue(v string) *SharePolicyUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableValue(v *string) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *SharePolicyUpdateOne) SetReason(v string) *SharePolicyUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *SharePolicyUpdateOne) SetNillableReason(v *string) *SharePolicyUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *SharePolicyUpdateOne) ClearReason() *SharePolicyUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// Mutation returns the SharePolicyMutation object of the builder.
func (_u *SharePolicyUpdateOne) Mutation() *SharePolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the SharePolicyUpdate builder.
func (_u *SharePolicyUpdateOne) Where(ps ...predicate.SharePolicy) *SharePolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SharePolicyUpdateOne) Select(field string, fields ...string) *SharePolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SharePolicy entity.
func (_u *SharePolicyUpdateOne) Save(ctx context.Context) (*SharePolicy, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SharePolicyUpdateOne) SaveX(ctx context.Context) *SharePolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SharePolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SharePolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SharePolicyUpdateOne) check() error {
	if v, ok := _u.mutation.ShareLinkID(); ok {
		if err := sharepolicy.ShareLinkIDValidator(v); err != nil {
			return &ValidationError{Name: "share_link_id", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.share_link_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := sharepolicy.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Method(); ok {
		if err := sharepolicy.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := sharepolicy.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := sharepolicy.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.reason": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SharePolicyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SharePolicyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SharePolicyUpdateOne) sqlSave(ctx context.Context) (_node *SharePolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sharepolicy.Table, sharepolicy.Columns, sqlgraph.NewFieldSpec(sharepolicy.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SharePolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharepolicy.FieldID)
		for _, f := range fields {
			if !sharepolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sharepolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(sharepolicy.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(sharepolicy.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(sharepolicy.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(sharepolicy.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(sharepolicy.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(sharepolicy.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(sharepolicy.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(sharepolicy.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(sharepolicy.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ShareLinkID(); ok {
		_spec.SetField(sharepolicy.FieldShareLinkID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(sharepolicy.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(sharepolicy.FieldMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(sharepolicy.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(sharepolicy.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(sharepolicy.FieldReason, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SharePolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sharepolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
