// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/sharepolicy"
)

// SharePolicyCreate is the builder for creating a SharePolicy entity.
type SharePolicyCreate struct {
	config
	mutation *SharePolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *SharePolicyCreate) SetCreateBy(v uint32) *SharePolicyCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableCreateBy(v *uint32) *SharePolicyCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *SharePolicyCreate) SetCreateTime(v time.Time) *SharePolicyCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableCreateTime(v *time.Time) *SharePolicyCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *SharePolicyCreate) SetUpdateTime(v time.Time) *SharePolicyCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableUpdateTime(v *time.Time) *SharePolicyCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *SharePolicyCreate) SetDeleteTime(v time.Time) *SharePolicyCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableDeleteTime(v *time.Time) *SharePolicyCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SharePolicyCreate) SetTenantID(v uint32) *SharePolicyCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableTenantID(v *uint32) *SharePolicyCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetShareLinkID sets the "share_link_id" field.
func (_c *SharePolicyCreate) SetShareLinkID(v string) *SharePolicyCreate {
	_c.mutation.SetShareLinkID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *SharePolicyCreate) SetType(v sharepolicy.Type) *SharePolicyCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *SharePolicyCreate) SetMethod(v sharepolicy.Method) *SharePolicyCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *SharePolicyCreate) SetValue(v string) *SharePolicyCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *SharePolicyCreate) SetReason(v string) *SharePolicyCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *SharePolicyCreate) SetNillableReason(v *string) *SharePolicyCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SharePolicyCreate) SetID(v string) *SharePolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SharePolicyMutation object of the builder.
func (_c *SharePolicyCreate) Mutation() *SharePolicyMutation {
	return _c.mutation
}

// Save creates the SharePolicy in the database.
func (_c *SharePolicyCreate) Save(ctx context.Context) (*SharePolicy, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SharePolicyCreate) SaveX(ctx context.Context) *SharePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharePolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharePolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SharePolicyCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := sharepolicy.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SharePolicyCreate) check() error {
	if _, ok := _c.mutation.ShareLinkID(); !ok {
		return &ValidationError{Name: "share_link_id", err: errors.New(`ent: missing required field "SharePolicy.share_link_id"`)}
	}
	if v, ok := _c.mutation.ShareLinkID(); ok {
		if err := sharepolicy.ShareLinkIDValidator(v); err != nil {
			return &ValidationError{Name: "share_link_id", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.share_link_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SharePolicy.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := sharepolicy.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "SharePolicy.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := sharepolicy.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SharePolicy.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := sharepolicy.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.value": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := sharepolicy.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sharepolicy.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SharePolicy.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SharePolicyCreate) sqlSave(ctx context.Context) (*SharePolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SharePolicy.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SharePolicyCreate) createSpec() (*SharePolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &SharePolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sharepolicy.Table, sqlgraph.NewFieldSpec(sharepolicy.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(sharepolicy.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(sharepolicy.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(sharepolicy.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(sharepolicy.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(sharepolicy.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ShareLinkID(); ok {
		_spec.SetField(sharepolicy.FieldShareLinkID, field.TypeString, value)
		_node.ShareLinkID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(sharepolicy.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(sharepolicy.FieldMethod, field.TypeEnum, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(sharepolicy.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(sharepolicy.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharePolicy.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharePolicyUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SharePolicyCreate) OnConflict(opts ...sql.ConflictOption) *SharePolicyUpsertOne {
	_c.conflict = opts
	return &SharePolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharePolicyCreate) OnConflictColumns(columns ...string) *SharePolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharePolicyUpsertOne{
		create: _c,
	}
}

type (
	// SharePolicyUpsertOne is the builder for "upsert"-ing
	//  one SharePolicy node.
	SharePolicyUpsertOne struct {
		create *SharePolicyCreate
	}

	// SharePolicyUpsert is the "OnConflict" setter.
	SharePolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *SharePolicyUpsert) SetCreateBy(v uint32) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateCreateBy() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *SharePolicyUpsert) AddCreateBy(v uint32) *SharePolicyUpsert {
	u.Add(sharepolicy.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SharePolicyUpsert) ClearCreateBy() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *SharePolicyUpsert) SetUpdateTime(v time.Time) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateUpdateTime() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SharePolicyUpsert) ClearUpdateTime() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *SharePolicyUpsert) SetDeleteTime(v time.Time) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateDeleteTime() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SharePolicyUpsert) ClearDeleteTime() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldDeleteTime)
	return u
}

// SetShareLinkID sets the "share_link_id" field.
func (u *SharePolicyUpsert) SetShareLinkID(v string) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldShareLinkID, v)
	return u
}

// UpdateShareLinkID sets the "share_link_id" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateShareLinkID() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldShareLinkID)
	return u
}

// SetType sets the "type" field.
func (u *SharePolicyUpsert) SetType(v sharepolicy.Type) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateType() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldType)
	return u
}

// SetMethod sets the "method" field.
func (u *SharePolicyUpsert) SetMethod(v sharepolicy.Method) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldMethod, v)
	return u
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateMethod() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldMethod)
	return u
}

// SetValue sets the "value" field.
func (u *SharePolicyUpsert) SetValue(v string) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateValue() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldValue)
	return u
}

// SetReason sets the "reason" field.
func (u *SharePolicyUpsert) SetReason(v string) *SharePolicyUpsert {
	u.Set(sharepolicy.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SharePolicyUpsert) UpdateReason() *SharePolicyUpsert {
	u.SetExcluded(sharepolicy.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *SharePolicyUpsert) ClearReason() *SharePolicyUpsert {
	u.SetNull(sharepolicy.FieldReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sharepolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SharePolicyUpsertOne) UpdateNewValues() *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(sharepolicy.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(sharepolicy.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(sharepolicy.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SharePolicyUpsertOne) Ignore() *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharePolicyUpsertOne) DoNothing() *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharePolicyCreate.OnConflict
// documentation for more info.
func (u *SharePolicyUpsertOne) Update(set func(*SharePolicyUpsert)) *SharePolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SharePolicyUpsertOne) SetCreateBy(v uint32) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SharePolicyUpsertOne) AddCreateBy(v uint32) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateCreateBy() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SharePolicyUpsertOne) ClearCreateBy() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SharePolicyUpsertOne) SetUpdateTime(v time.Time) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateUpdateTime() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SharePolicyUpsertOne) ClearUpdateTime() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SharePolicyUpsertOne) SetDeleteTime(v time.Time) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateDeleteTime() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SharePolicyUpsertOne) ClearDeleteTime() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearDeleteTime()
	})
}

// SetShareLinkID sets the "share_link_id" field.
func (u *SharePolicyUpsertOne) SetShareLinkID(v string) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetShareLinkID(v)
	})
}

// UpdateShareLinkID sets the "share_link_id" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateShareLinkID() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateShareLinkID()
	})
}

// SetType sets the "type" field.
func (u *SharePolicyUpsertOne) SetType(v sharepolicy.Type) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateType() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateType()
	})
}

// SetMethod sets the "method" field.
func (u *SharePolicyUpsertOne) SetMethod(v sharepolicy.Method) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateMethod() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateMethod()
	})
}

// SetValue sets the "value" field.
func (u *SharePolicyUpsertOne) SetValue(v string) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateValue() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateValue()
	})
}

// SetReason sets the "reason" field.
func (u *SharePolicyUpsertOne) SetReason(v string) *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SharePolicyUpsertOne) UpdateReason() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *SharePolicyUpsertOne) ClearReason() *SharePolicyUpsertOne {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearReason()
	})
}

// Exec executes the query.
func (u *SharePolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharePolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharePolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SharePolicyUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SharePolicyUpsertOne.ID is not supported by MySQL driver. Use SharePolicyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SharePolicyUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SharePolicyCreateBulk is the builder for creating many SharePolicy entities in bulk.
type SharePolicyCreateBulk struct {
	config
	err      error
	builders []*SharePolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the SharePolicy entities in the database.
func (_c *SharePolicyCreateBulk) Save(ctx context.Context) ([]*SharePolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SharePolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharePolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SharePolicyCreateBulk) SaveX(ctx context.Context) []*SharePolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SharePolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SharePolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SharePolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SharePolicyUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *SharePolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *SharePolicyUpsertBulk {
	_c.conflict = opts
	return &SharePolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SharePolicyCreateBulk) OnConflictColumns(columns ...string) *SharePolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SharePolicyUpsertBulk{
		create: _c,
	}
}

// SharePolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of SharePolicy nodes.
type SharePolicyUpsertBulk struct {
	create *SharePolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sharepolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SharePolicyUpsertBulk) UpdateNewValues() *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(sharepolicy.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(sharepolicy.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(sharepolicy.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SharePolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SharePolicyUpsertBulk) Ignore() *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SharePolicyUpsertBulk) DoNothing() *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SharePolicyCreateBulk.OnConflict
// documentation for more info.
func (u *SharePolicyUpsertBulk) Update(set func(*SharePolicyUpsert)) *SharePolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SharePolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *SharePolicyUpsertBulk) SetCreateBy(v uint32) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *SharePolicyUpsertBulk) AddCreateBy(v uint32) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateCreateBy() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *SharePolicyUpsertBulk) ClearCreateBy() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *SharePolicyUpsertBulk) SetUpdateTime(v time.Time) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateUpdateTime() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *SharePolicyUpsertBulk) ClearUpdateTime() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *SharePolicyUpsertBulk) SetDeleteTime(v time.Time) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateDeleteTime() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *SharePolicyUpsertBulk) ClearDeleteTime() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearDeleteTime()
	})
}

// SetShareLinkID sets the "share_link_id" field.
func (u *SharePolicyUpsertBulk) SetShareLinkID(v string) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetShareLinkID(v)
	})
}

// UpdateShareLinkID sets the "share_link_id" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateShareLinkID() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateShareLinkID()
	})
}

// SetType sets the "type" field.
func (u *SharePolicyUpsertBulk) SetType(v sharepolicy.Type) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateType() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateType()
	})
}

// SetMethod sets the "method" field.
func (u *SharePolicyUpsertBulk) SetMethod(v sharepolicy.Method) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetMethod(v)
	})
}

// UpdateMethod sets the "method" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateMethod() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateMethod()
	})
}

// SetValue sets the "value" field.
func (u *SharePolicyUpsertBulk) SetValue(v string) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateValue() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateValue()
	})
}

// SetReason sets the "reason" field.
func (u *SharePolicyUpsertBulk) SetReason(v string) *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SharePolicyUpsertBulk) UpdateReason() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *SharePolicyUpsertBulk) ClearReason() *SharePolicyUpsertBulk {
	return u.Update(func(s *SharePolicyUpsert) {
		s.ClearReason()
	})
}

// Exec executes the query.
func (u *SharePolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SharePolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SharePolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SharePolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
