// Code generated by ent, DO NOT EDIT.

package emailtemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldCreateBy, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldUpdateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldName, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldSubject, v))
}

// HTMLBody applies equality check predicate on the "html_body" field. It's identical to HTMLBodyEQ.
func HTMLBody(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldHTMLBody, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldIsDefault, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotNull(FieldCreateBy))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotNull(FieldUpdateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotNull(FieldTenantID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldContainsFold(FieldName, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldContainsFold(FieldSubject, v))
}

// HTMLBodyEQ applies the EQ predicate on the "html_body" field.
func HTMLBodyEQ(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldHTMLBody, v))
}

// HTMLBodyNEQ applies the NEQ predicate on the "html_body" field.
func HTMLBodyNEQ(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldHTMLBody, v))
}

// HTMLBodyIn applies the In predicate on the "html_body" field.
func HTMLBodyIn(vs ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldIn(FieldHTMLBody, vs...))
}

// HTMLBodyNotIn applies the NotIn predicate on the "html_body" field.
func HTMLBodyNotIn(vs ...string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNotIn(FieldHTMLBody, vs...))
}

// HTMLBodyGT applies the GT predicate on the "html_body" field.
func HTMLBodyGT(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGT(FieldHTMLBody, v))
}

// HTMLBodyGTE applies the GTE predicate on the "html_body" field.
func HTMLBodyGTE(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldGTE(FieldHTMLBody, v))
}

// HTMLBodyLT applies the LT predicate on the "html_body" field.
func HTMLBodyLT(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLT(FieldHTMLBody, v))
}

// HTMLBodyLTE applies the LTE predicate on the "html_body" field.
func HTMLBodyLTE(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldLTE(FieldHTMLBody, v))
}

// HTMLBodyContains applies the Contains predicate on the "html_body" field.
func HTMLBodyContains(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldContains(FieldHTMLBody, v))
}

// HTMLBodyHasPrefix applies the HasPrefix predicate on the "html_body" field.
func HTMLBodyHasPrefix(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldHasPrefix(FieldHTMLBody, v))
}

// HTMLBodyHasSuffix applies the HasSuffix predicate on the "html_body" field.
func HTMLBodyHasSuffix(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldHasSuffix(FieldHTMLBody, v))
}

// HTMLBodyEqualFold applies the EqualFold predicate on the "html_body" field.
func HTMLBodyEqualFold(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEqualFold(FieldHTMLBody, v))
}

// HTMLBodyContainsFold applies the ContainsFold predicate on the "html_body" field.
func HTMLBodyContainsFold(v string) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldContainsFold(FieldHTMLBody, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.FieldNEQ(FieldIsDefault, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EmailTemplate) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EmailTemplate) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EmailTemplate) predicate.EmailTemplate {
	return predicate.EmailTemplate(sql.NotPredicates(p))
}
