// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SharePolicy is the predicate function for sharepolicy builders.
type SharePolicy func(*sql.Selector)

// SharedLink is the predicate function for sharedlink builders.
type SharedLink func(*sql.Selector)
