// Code generated by ent, DO NOT EDIT.

package sharepolicy

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sharepolicy type in the database.
	Label = "share_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldShareLinkID holds the string denoting the share_link_id field in the database.
	FieldShareLinkID = "share_link_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// Table holds the table name of the sharepolicy in the database.
	Table = "sharing_share_policies"
)

// Columns holds all SQL columns for sharepolicy fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldCreateTime,
	FieldUpdateTime,
	FieldDeleteTime,
	FieldTenantID,
	FieldShareLinkID,
	FieldType,
	FieldMethod,
	FieldValue,
	FieldReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/go-tangra/go-tangra-sharing/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// ShareLinkIDValidator is a validator for the "share_link_id" field. It is called by the builders before save.
	ShareLinkIDValidator func(string) error
	// ValueValidator is a validator for the "value" field. It is called by the builders before save.
	ValueValidator func(string) error
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeBLACKLIST Type = "BLACKLIST"
	TypeWHITELIST Type = "WHITELIST"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeBLACKLIST, TypeWHITELIST:
		return nil
	default:
		return fmt.Errorf("sharepolicy: invalid enum value for type field: %q", _type)
	}
}

// Method defines the type for the "method" enum field.
type Method string

// Method values.
const (
	MethodIP      Method = "IP"
	MethodMAC     Method = "MAC"
	MethodREGION  Method = "REGION"
	MethodTIME    Method = "TIME"
	MethodDEVICE  Method = "DEVICE"
	MethodNETWORK Method = "NETWORK"
)

func (m Method) String() string {
	return string(m)
}

// MethodValidator is a validator for the "method" field enum values. It is called by the builders before save.
func MethodValidator(m Method) error {
	switch m {
	case MethodIP, MethodMAC, MethodREGION, MethodTIME, MethodDEVICE, MethodNETWORK:
		return nil
	default:
		return fmt.Errorf("sharepolicy: invalid enum value for method field: %q", m)
	}
}

// OrderOption defines the ordering options for the SharePolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByShareLinkID orders the results by the share_link_id field.
func ByShareLinkID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShareLinkID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}
