// Code generated by ent, DO NOT EDIT.

package sharepolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-sharing/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldTenantID, v))
}

// ShareLinkID applies equality check predicate on the "share_link_id" field. It's identical to ShareLinkIDEQ.
func ShareLinkID(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldShareLinkID, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldValue, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldReason, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldTenantID))
}

// ShareLinkIDEQ applies the EQ predicate on the "share_link_id" field.
func ShareLinkIDEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldShareLinkID, v))
}

// ShareLinkIDNEQ applies the NEQ predicate on the "share_link_id" field.
func ShareLinkIDNEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldShareLinkID, v))
}

// ShareLinkIDIn applies the In predicate on the "share_link_id" field.
func ShareLinkIDIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldShareLinkID, vs...))
}

// ShareLinkIDNotIn applies the NotIn predicate on the "share_link_id" field.
func ShareLinkIDNotIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldShareLinkID, vs...))
}

// ShareLinkIDGT applies the GT predicate on the "share_link_id" field.
func ShareLinkIDGT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldShareLinkID, v))
}

// ShareLinkIDGTE applies the GTE predicate on the "share_link_id" field.
func ShareLinkIDGTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldShareLinkID, v))
}

// ShareLinkIDLT applies the LT predicate on the "share_link_id" field.
func ShareLinkIDLT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldShareLinkID, v))
}

// ShareLinkIDLTE applies the LTE predicate on the "share_link_id" field.
func ShareLinkIDLTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldShareLinkID, v))
}

// ShareLinkIDContains applies the Contains predicate on the "share_link_id" field.
func ShareLinkIDContains(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContains(FieldShareLinkID, v))
}

// ShareLinkIDHasPrefix applies the HasPrefix predicate on the "share_link_id" field.
func ShareLinkIDHasPrefix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasPrefix(FieldShareLinkID, v))
}

// ShareLinkIDHasSuffix applies the HasSuffix predicate on the "share_link_id" field.
func ShareLinkIDHasSuffix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasSuffix(FieldShareLinkID, v))
}

// ShareLinkIDEqualFold applies the EqualFold predicate on the "share_link_id" field.
func ShareLinkIDEqualFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEqualFold(FieldShareLinkID, v))
}

// ShareLinkIDContainsFold applies the ContainsFold predicate on the "share_link_id" field.
func ShareLinkIDContainsFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContainsFold(FieldShareLinkID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldType, vs...))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v Method) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v Method) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...Method) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...Method) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldMethod, vs...))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContainsFold(FieldValue, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.SharePolicy {
	return predicate.SharePolicy(sql.FieldContainsFold(FieldReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharePolicy) predicate.SharePolicy {
	return predicate.SharePolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharePolicy) predicate.SharePolicy {
	return predicate.SharePolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharePolicy) predicate.SharePolicy {
	return predicate.SharePolicy(sql.NotPredicates(p))
}
