// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SharingEmailTemplatesColumns holds the columns for the "sharing_email_templates" table.
	SharingEmailTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Template name"},
		{Name: "subject", Type: field.TypeString, Size: 1024, Comment: "Email subject (Go template)"},
		{Name: "html_body", Type: field.TypeString, Size: 2147483647, Comment: "Email HTML body (Go html/template)"},
		{Name: "is_default", Type: field.TypeBool, Comment: "Whether this is the default template for the tenant", Default: false},
	}
	// SharingEmailTemplatesTable holds the schema information for the "sharing_email_templates" table.
	SharingEmailTemplatesTable = &schema.Table{
		Name:       "sharing_email_templates",
		Columns:    SharingEmailTemplatesColumns,
		PrimaryKey: []*schema.Column{SharingEmailTemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "emailtemplate_tenant_id_name",
				Unique:  true,
				Columns: []*schema.Column{SharingEmailTemplatesColumns[6], SharingEmailTemplatesColumns[7]},
			},
			{
				Name:    "emailtemplate_tenant_id_is_default",
				Unique:  false,
				Columns: []*schema.Column{SharingEmailTemplatesColumns[6], SharingEmailTemplatesColumns[10]},
			},
			{
				Name:    "emailtemplate_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SharingEmailTemplatesColumns[6]},
			},
		},
	}
	// SharingSharePoliciesColumns holds the columns for the "sharing_share_policies" table.
	SharingSharePoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "share_link_id", Type: field.TypeString, Size: 36, Comment: "FK to shared_link.id"},
		{Name: "type", Type: field.TypeEnum, Comment: "Restriction type: BLACKLIST (deny) or WHITELIST (allow)", Enums: []string{"BLACKLIST", "WHITELIST"}},
		{Name: "method", Type: field.TypeEnum, Comment: "Restriction method", Enums: []string{"IP", "MAC", "REGION", "TIME", "DEVICE", "NETWORK"}},
		{Name: "value", Type: field.TypeString, Size: 512, Comment: "Restriction value (IP, CIDR range, MAC, region code, time range, device ID)"},
		{Name: "reason", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Explanation for this restriction"},
	}
	// SharingSharePoliciesTable holds the schema information for the "sharing_share_policies" table.
	SharingSharePoliciesTable = &schema.Table{
		Name:       "sharing_share_policies",
		Columns:    SharingSharePoliciesColumns,
		PrimaryKey: []*schema.Column{SharingSharePoliciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sharepolicy_share_link_id",
				Unique:  false,
				Columns: []*schema.Column{SharingSharePoliciesColumns[6]},
			},
			{
				Name:    "sharepolicy_share_link_id_type_method",
				Unique:  false,
				Columns: []*schema.Column{SharingSharePoliciesColumns[6], SharingSharePoliciesColumns[7], SharingSharePoliciesColumns[8]},
			},
		},
	}
	// SharingSharedLinksColumns holds the columns for the "sharing_shared_links" table.
	SharingSharedLinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "resource_type", Type: field.TypeEnum, Comment: "Type of resource being shared", Enums: []string{"SECRET", "DOCUMENT"}},
		{Name: "resource_id", Type: field.TypeString, Size: 255, Comment: "ID of the shared resource"},
		{Name: "resource_name", Type: field.TypeString, Size: 255, Comment: "Display name of the shared resource"},
		{Name: "token", Type: field.TypeString, Unique: true, Size: 64, Comment: "Unique share token (64 hex chars)"},
		{Name: "encrypted_content", Type: field.TypeBytes, Comment: "AES-256-GCM encrypted content"},
		{Name: "encryption_nonce", Type: field.TypeBytes, Comment: "AES-256-GCM nonce"},
		{Name: "recipient_email", Type: field.TypeString, Size: 320, Comment: "Recipient email address"},
		{Name: "message", Type: field.TypeString, Nullable: true, Size: 2048, Comment: "Optional message to recipient"},
		{Name: "template_id", Type: field.TypeString, Nullable: true, Size: 36, Comment: "Email template ID used"},
		{Name: "viewed", Type: field.TypeBool, Comment: "Whether the share has been viewed", Default: false},
		{Name: "viewed_at", Type: field.TypeTime, Nullable: true, Comment: "When the share was viewed"},
		{Name: "viewed_ip", Type: field.TypeString, Nullable: true, Size: 45, Comment: "IP address of viewer"},
		{Name: "revoked", Type: field.TypeBool, Comment: "Whether the share has been revoked", Default: false},
	}
	// SharingSharedLinksTable holds the schema information for the "sharing_shared_links" table.
	SharingSharedLinksTable = &schema.Table{
		Name:       "sharing_shared_links",
		Columns:    SharingSharedLinksColumns,
		PrimaryKey: []*schema.Column{SharingSharedLinksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sharedlink_token",
				Unique:  true,
				Columns: []*schema.Column{SharingSharedLinksColumns[9]},
			},
			{
				Name:    "sharedlink_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{SharingSharedLinksColumns[6], SharingSharedLinksColumns[7]},
			},
			{
				Name:    "sharedlink_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SharingSharedLinksColumns[5]},
			},
			{
				Name:    "sharedlink_recipient_email",
				Unique:  false,
				Columns: []*schema.Column{SharingSharedLinksColumns[12]},
			},
			{
				Name:    "sharedlink_tenant_id_viewed",
				Unique:  false,
				Columns: []*schema.Column{SharingSharedLinksColumns[5], SharingSharedLinksColumns[15]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SharingEmailTemplatesTable,
		SharingSharePoliciesTable,
		SharingSharedLinksTable,
	}
)

func init() {
	SharingEmailTemplatesTable.Annotation = &entsql.Annotation{
		Table: "sharing_email_templates",
	}
	SharingSharePoliciesTable.Annotation = &entsql.Annotation{
		Table: "sharing_share_policies",
	}
	SharingSharedLinksTable.Annotation = &entsql.Annotation{
		Table: "sharing_shared_links",
	}
}
