// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	gocontext "context"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-common/viewer"
	"github.com/go-tangra/go-tangra-sharing/internal/cert"
	"github.com/go-tangra/go-tangra-sharing/internal/data"
	"github.com/go-tangra/go-tangra-sharing/internal/metrics"
	"github.com/go-tangra/go-tangra-sharing/internal/server"
	"github.com/go-tangra/go-tangra-sharing/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	sharedLinkRepo := data.NewSharedLinkRepo(context, entClient)
	sharePolicyRepo := data.NewSharePolicyRepo(context, entClient)
	client, err := data.NewRegistrationClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	moduleDialer := data.NewModuleDialer(context, client)
	wardenClient, cleanup2, err := data.NewWardenClient(context, moduleDialer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	paperlessClient, cleanup3, err := data.NewPaperlessClient(context, moduleDialer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationClient, cleanup4, err := data.NewNotificationClient(context, moduleDialer)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	shareService := service.NewShareService(context, sharedLinkRepo, sharePolicyRepo, wardenClient, paperlessClient, notificationClient)
	backupService := service.NewBackupService(context, entClient)
	collector := metrics.NewCollector(context)
	statisticsRepo := data.NewStatisticsRepo(context, entClient)
	grpcServer := server.NewGRPCServer(context, v, collector, shareService, backupService)
	httpServer := server.NewHTTPServer(context, shareService)

	// Seed Prometheus metrics from database
	seedCtx := viewer.NewSystemViewerContext(gocontext.Background())
	collector.Seed(seedCtx, statisticsRepo)

	app := newApp(context, grpcServer, httpServer, client)
	return app, func() {
		collector.Stop(gocontext.Background())
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
