// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-sharing/internal/cert"
	"github.com/go-tangra/go-tangra-sharing/internal/data"
	"github.com/go-tangra/go-tangra-sharing/internal/server"
	"github.com/go-tangra/go-tangra-sharing/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	sharedLinkRepo := data.NewSharedLinkRepo(context, entClient)
	emailTemplateRepo := data.NewEmailTemplateRepo(context, entClient)
	sharePolicyRepo := data.NewSharePolicyRepo(context, entClient)
	wardenClient, cleanup2, err := data.NewWardenClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	paperlessClient, cleanup3, err := data.NewPaperlessClient(context)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sender := data.NewMailSender()
	shareService := service.NewShareService(context, sharedLinkRepo, emailTemplateRepo, sharePolicyRepo, wardenClient, paperlessClient, sender)
	templateService := service.NewTemplateService(context, emailTemplateRepo)
	grpcServer := server.NewGRPCServer(context, certManager, shareService, templateService)
	httpServer := server.NewHTTPServer(context, shareService)
	app := newApp(context, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
